//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class APCompanyParm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APCompanyParm()
        {
            this.APTransactions = new HashSet<APTran>();
            this.APDocuments = new HashSet<APDocument>();
            this.bAPHBs = new HashSet<APBatchHeader>();
        }
    
        [Key]
		public byte APCo { get; set; }
        public byte GLCo { get; set; }
        public string ExpJrnl { get; set; }
        public byte GLExpInterfaceLvl { get; set; }
        public string GLExpSummaryDesc { get; set; }
        public string GLExpTransDesc { get; set; }
        public string GLJobDetailDesc { get; set; }
        public string GLInvDetailDesc { get; set; }
        public string GLEquipDetailDesc { get; set; }
        public string GLExpDetailDesc { get; set; }
        public string PayJrnl { get; set; }
        public byte GLPayInterfaceLvl { get; set; }
        public string GLPayDetailDesc { get; set; }
        public string GLPaySummaryDesc { get; set; }
        public string DiscOffGLAcct { get; set; }
        public string DiscTakenGLAcct { get; set; }
        public Nullable<byte> ExpPayType { get; set; }
        public Nullable<byte> JobPayType { get; set; }
        public Nullable<byte> SubPayType { get; set; }
        public Nullable<byte> RetPayType { get; set; }
        public string OverridePayType { get; set; }
        public string RetHoldCode { get; set; }
        public byte CMCo { get; set; }
        public Nullable<short> CMAcct { get; set; }
        public byte CMInterfaceLvl { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public byte JCInterfaceLvl { get; set; }
        public string NetAmtOpt { get; set; }
        public Nullable<byte> INCo { get; set; }
        public byte INInterfaceLvl { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public byte EMInterfaceLvl { get; set; }
        public string InvTotYN { get; set; }
        public string SLTotYN { get; set; }
        public string SLCompChkYN { get; set; }
        public string SLAllowPayYN { get; set; }
        public string POTotYN { get; set; }
        public string POCompChkYN { get; set; }
        public string POAllowPayYN { get; set; }
        public byte ChkLines { get; set; }
        public string AuditCoParams { get; set; }
        public string AuditPayTypes { get; set; }
        public string AuditVendors { get; set; }
        public string AuditHold { get; set; }
        public string AuditComp { get; set; }
        public string AuditRecur { get; set; }
        public string AuditTrans { get; set; }
        public string AuditPay { get; set; }
        public string Notes { get; set; }
        public string APRefUnqYN { get; set; }
        public string CheckReportTitle { get; set; }
        public string OverFlowReportTitle { get; set; }
        public string JobLineDescDfltYN { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public byte APRefUnq { get; set; }
        public string AllCompChkYN { get; set; }
        public string AllAllowPayYN { get; set; }
        public string UseTaxDiscountYN { get; set; }
        public string PMVendUpdYN { get; set; }
        public string PMVendAddYN { get; set; }
        public string ICRptYN { get; set; }
        public string ICRptTitle { get; set; }
        public decimal ICPayAmt { get; set; }
        public string PayCategoryYN { get; set; }
        public Nullable<int> PayCategory { get; set; }
        public string AuditUnappInv { get; set; }
        public string InvExceedRecvdYN { get; set; }
        public string POItemTotYN { get; set; }
        public long KeyID { get; set; }
        public string JobLineJobPhaseUMDfltYN { get; set; }
        public string EMLineDescDfltYN { get; set; }
        public string AttachBatchReportsYN { get; set; }
        public string AttachVendorPayInfoYN { get; set; }
        public string CheckReportTitleByVendor { get; set; }
        public string EFTRemittanceReport { get; set; }
        public string EFTRemittanceReportByVendor { get; set; }
        public Nullable<int> VendorPayAttachTypeID { get; set; }
        public string AuditTransHoldCodeYN { get; set; }
        public string TaxBasisNetRetgYN { get; set; }
        public Nullable<byte> SMPayType { get; set; }
        public string POItemLineTotYN { get; set; }
        public string InvExceedRecvdLineYN { get; set; }
        public string CreditSvcRemittanceReport { get; set; }
        public string CreditSvcRemittanceReportByVendor { get; set; }
        public byte APCreditService { get; set; }
        public Nullable<byte> CSCMCo { get; set; }
        public Nullable<short> CSCMAcct { get; set; }
        public string CDAcctCode { get; set; }
        public string CDCustID { get; set; }
        public string CDCodeWord { get; set; }
        public Nullable<decimal> TCCo { get; set; }
        public Nullable<decimal> TCAcct { get; set; }
        public string CSDataFilePath { get; set; }
        public string FtpUrl { get; set; }
        public Nullable<int> FtpPort { get; set; }
        public string FtpUserID { get; set; }
        public string FtpPassword { get; set; }
        public string CDLocationCode { get; set; }
        public string CDInvoiceComments { get; set; }
        public string CBNAPProgramAcct { get; set; }
        public string APRefCaseInsensitiveYN { get; set; }
        public string APUIAutoReadyYN { get; set; }
        public Nullable<int> udDftMerchantVendorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APTran> APTransactions { get; set; }
        public virtual HQCompanyParm HQCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APDocument> APDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APBatchHeader> bAPHBs { get; set; }
    }
}
