//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class APDocumentWorkFlow
    {
        [Key]
		public byte APCo { get; set; }
        [Key]
		public int DocId { get; set; }
        public int Status { get; set; }
        public System.DateTime StatusDate { get; set; }
        [Key]
		public int LineId { get; set; }
        public string AssignedTo { get; set; }
        public System.DateTime AssignedOn { get; set; }
        public Nullable<int> AssignedStatus { get; set; }
        public Nullable<System.DateTime> EmailedDate { get; set; }
        public Nullable<int> NotificationId { get; set; }
        public string Active { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Comments { get; set; }
        public long KeyID { get; set; }
    
        public virtual APDocument Document { get; set; }
        public virtual WebUser AssignedUser { get; set; }
        public virtual WebUser CreatedUSer { get; set; }
    }
}
