//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class APDocumentLine
    {
        [Key]
		public byte APCo { get; set; }
        [Key]
		public int DocId { get; set; }
        [Key]
		public int SeqId { get; set; }
        [Key]
		public short LineId { get; set; }
        public Nullable<int> tDivisionId { get; set; }
        public byte tLineTypeId { get; set; }
        public Nullable<byte> POCo { get; set; }
        public string tPO { get; set; }
        public Nullable<short> tPOItemId { get; set; }
        public Nullable<int> POItemLine { get; set; }
        public Nullable<byte> tPOItemTypeId { get; set; }
        public string SL { get; set; }
        public Nullable<short> SLItem { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string tJobId { get; set; }
        public Nullable<byte> PhaseGroupId { get; set; }
        public string tPhaseId { get; set; }
        public Nullable<byte> tJCCType { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public string WO { get; set; }
        public Nullable<short> WOItem { get; set; }
        public string tEquipmentId { get; set; }
        public Nullable<byte> EMGroupId { get; set; }
        public string tCostCodeId { get; set; }
        public Nullable<byte> tEMCType { get; set; }
        public string CompTypeId { get; set; }
        public string Component { get; set; }
        public Nullable<byte> INCo { get; set; }
        public string Loc { get; set; }
        public Nullable<byte> MatlGroup { get; set; }
        public string MaterialId { get; set; }
        public Nullable<byte> GLCo { get; set; }
        public string tGLAcct { get; set; }
        public string tDescription { get; set; }
        public string UM { get; set; }
        public Nullable<decimal> Units { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string ECM { get; set; }
        public Nullable<byte> VendorGroupId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<byte> PayType { get; set; }
        public Nullable<decimal> GrossAmt { get; set; }
        public Nullable<decimal> MiscAmt { get; set; }
        public string MiscYN { get; set; }
        public Nullable<byte> TaxGroupId { get; set; }
        public string tTaxCodeId { get; set; }
        public Nullable<byte> tTaxTypeId { get; set; }
        public Nullable<decimal> TaxBasis { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<decimal> Retainage { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> BurUnitCost { get; set; }
        public string BECM { get; set; }
        public Nullable<decimal> SMChange { get; set; }
        public string Notes { get; set; }
        public string POPayTypeYN { get; set; }
        public Nullable<int> PayCategory { get; set; }
        public Nullable<long> SLDetailKeyID { get; set; }
        public string Receiver_ { get; set; }
        public Nullable<long> SLKeyID { get; set; }
        public Nullable<byte> SMCo { get; set; }
        public Nullable<int> SMWorkOrder { get; set; }
        public Nullable<int> Scope { get; set; }
        public string SMStandardItem { get; set; }
        public Nullable<long> APTLKeyID { get; set; }
        public Nullable<short> SMCostType { get; set; }
        public Nullable<byte> SMJCCostType { get; set; }
        public Nullable<byte> SMPhaseGroup { get; set; }
        public string SubjToOnCostYN { get; set; }
        public string SMPhase { get; set; }
        public Nullable<decimal> SMTaxLiability { get; set; }
        public long KeyID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual EMCostCode EMCostCode { get; set; }
        public virtual EMCostType EMCostType { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobPhase JobPhase { get; set; }
        public virtual CostType JCCostType { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual PurchaseOrderItem POItem { get; set; }
        public virtual CompanyDivision Division { get; set; }
        public virtual TaxCode TaxCode { get; set; }
        public virtual JobPhaseCost JobPhaseCost { get; set; }
        public virtual APDocument Document { get; set; }
    }
}
