//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class APPaymentLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPaymentLine()
        {
            this.APTransLinePayments = new HashSet<APTransLinePayment>();
        }
    
        [Key]
		public byte APCo { get; set; }
        [Key]
		public byte CMCo { get; set; }
        [Key]
		public short CMAcct { get; set; }
        [Key]
		public string PayMethod { get; set; }
        [Key]
		public string CMRef { get; set; }
        [Key]
		public byte CMRefSeq { get; set; }
        [Key]
		public short EFTSeq { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public int APTrans { get; set; }
        public string APRef { get; set; }
        public string Description { get; set; }
        public System.DateTime InvDate { get; set; }
        public decimal Gross { get; set; }
        public decimal Retainage { get; set; }
        public decimal PrevPaid { get; set; }
        public decimal PrevDiscTaken { get; set; }
        public decimal Balance { get; set; }
        public decimal DiscTaken { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public Nullable<decimal> TotTaxAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APTransLinePayment> APTransLinePayments { get; set; }
        public virtual APPayment Payment { get; set; }
    }
}
