//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class BDPackageCrew
    {
        [Key]
		public byte BDCo { get; set; }
        [Key]
		public int BidId { get; set; }
        [Key]
		public int PackageId { get; set; }
        [Key]
		public int SeqId { get; set; }
        public string CrewId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual Crew Crew { get; set; }
        public virtual BidPackage Package { get; set; }
    }
}
