//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bid()
        {
            this.BoreLines = new HashSet<BidBoreLine>();
            this.Packages = new HashSet<BidPackage>();
            this.Customers = new HashSet<BidCustomer>();
            this.XXX_WorkFlows = new HashSet<BidWorkFlowAssignment>();
            this.Scopes = new HashSet<BidProposalScope>();
            this.budBDPS = new HashSet<BidPackageScope>();
            this.PMLocates = new HashSet<PMLocate>();
            this.PMLocateRequests = new HashSet<PMLocateRequest>();
        }
    
        [Key]
		public byte BDCo { get; set; }
        [Key]
		public int BidId { get; set; }
        public Nullable<System.DateTime> BidDate { get; set; }
        public string tDescription { get; set; }
        public Nullable<int> tCustomerId { get; set; }
        public Nullable<int> tFirmId { get; set; }
        public string Location { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> tStatusId { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string ImportFileName { get; set; }
        public Nullable<int> BidType { get; set; }
        public Nullable<decimal> DirtGM { get; set; }
        public Nullable<decimal> RockGM { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> tStartDate { get; set; }
        public Nullable<int> tDivisionId { get; set; }
        public Nullable<int> ForumId { get; set; }
        public Nullable<decimal> MobePrice { get; set; }
        public Nullable<decimal> DeMobePrice { get; set; }
        public Nullable<decimal> DelayDeMobePrice { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> tIndustryId { get; set; }
        public Nullable<int> ProjectMangerId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public Nullable<int> WorkFlowId { get; set; }
        public string StateCodeId { get; set; }
        public Nullable<byte> CustGroupId { get; set; }
        public Nullable<int> MapSetId { get; set; }
        public string tGPS { get; set; }
        public Nullable<decimal> GPSLong { get; set; }
        public Nullable<decimal> GPSLat { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Firm Firm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLine> BoreLines { get; set; }
        public virtual WebUser CreatedUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackage> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidCustomer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidWorkFlowAssignment> XXX_WorkFlows { get; set; }
        public virtual HQCompanyParm Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidProposalScope> Scopes { get; set; }
        public virtual Forum Forum { get; set; }
        public virtual JCIndustry Industry { get; set; }
        public virtual ProjectDivision Division { get; set; }
        public virtual WorkFlow WorkFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackageScope> budBDPS { get; set; }
        public virtual HQAttachment HQAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMLocate> PMLocates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMLocateRequest> PMLocateRequests { get; set; }
        public virtual WPMapSet WPMapSet { get; set; }
    }
}
