//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class BidBoreLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BidBoreLine()
        {
            this.Passes = new HashSet<BidBoreLinePass>();
            this.CostItems = new HashSet<BidBoreLineCostItem>();
            this.DNU_Gantt = new HashSet<BidProductionDay>();
            this.vBoreLineCostItems = new HashSet<vBidBoreLineCostItem>();
            this.bPMEHs = new HashSet<ProjectBudget>();
            this.IntersectBores = new HashSet<BidBoreLine>();
            this.budPMLAs = new HashSet<PMLocateAssignment>();
        }
    
        [Key]
		public byte BDCo { get; set; }
        [Key]
		public int BidId { get; set; }
        [Key]
		public int BoreId { get; set; }
        public string tDescription { get; set; }
        public Nullable<decimal> tFootage { get; set; }
        public Nullable<decimal> tPipeSize { get; set; }
        public Nullable<int> tGroundDensityId { get; set; }
        public string tRigCategoryId { get; set; }
        public string CrewId { get; set; }
        public Nullable<int> tCrewCount { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public Nullable<int> tBoreTypeId { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> tStatusId { get; set; }
        public Nullable<int> IntersectBoreId { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string tJobId { get; set; }
        public Nullable<int> tCustomerId { get; set; }
        public Nullable<int> tDivisionId { get; set; }
        public string tCustomerReference { get; set; }
        public Nullable<decimal> CurFootage { get; set; }
        public Nullable<bool> RecalcNeeded { get; set; }
        public Nullable<int> tIndustryId { get; set; }
        public Nullable<int> tMarketId { get; set; }
        public string RigId { get; set; }
        public Nullable<int> GanttId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual Bid Bid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLinePass> Passes { get; set; }
        public virtual GroundDensity GroundDensity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLineCostItem> CostItems { get; set; }
        public virtual EquipmentCategory RigCategory { get; set; }
        public virtual BidBoreType BoreType { get; set; }
        public virtual BidPackage Package { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidProductionDay> DNU_Gantt { get; set; }
        public virtual PMProjectGanttTask ProjectGanttTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vBidBoreLineCostItem> vBoreLineCostItems { get; set; }
        public virtual ProjectDivision Division { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudget> bPMEHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLine> IntersectBores { get; set; }
        public virtual BidBoreLine Intersect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMLocateAssignment> budPMLAs { get; set; }
    }
}
