//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class BidProposalScope
    {
        [Key]
		public byte BDCo { get; set; }
        [Key]
		public int BidId { get; set; }
        [Key]
		public int ScopeTypeId { get; set; }
        [Key]
		public int LineId { get; set; }
        public string Notes { get; set; }
        public byte Status { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
    
        public virtual Bid Bid { get; set; }
    }
}
