//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class BidPackageCostItem
    {
        [Key]
		public byte BDCo { get; set; }
        [Key]
		public int BidId { get; set; }
        [Key]
		public int PackageId { get; set; }
        [Key]
		public int LineId { get; set; }
        public string tBudgetCodeId { get; set; }
        public Nullable<byte> tApplied { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Units { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public Nullable<decimal> tMultiplier { get; set; }
        public Nullable<int> ShiftCnt { get; set; }
    
        public virtual ProjectBudgetCode BudgetCode { get; set; }
        public virtual BidPackage Package { get; set; }
    }
}
