//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class budCMTH_Cross
    {
        [Key]
		public byte Co { get; set; }
        [Key]
		public long TransId { get; set; }
        [Key]
		public string UniqueTransId { get; set; }
        [Key]
		public string NewUniqueTransId { get; set; }
    }
}
