//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class budEMCR
    {
        [Key]
		public byte EMCo { get; set; }
        [Key]
		public string CategoryId { get; set; }
        [Key]
		public string UM { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
    
        public virtual EquipmentCategory Category { get; set; }
    }
}
