//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class budPMLM_Owners
    {
        [Key]
		public string Owner { get; set; }
        public Nullable<byte> VendorGroupId { get; set; }
        public Nullable<int> FirmNumber { get; set; }
    }
}
