//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class CompanyDivision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyDivision()
        {
            this.PREmployees = new HashSet<Employee>();
            this.CMTransactionCodes = new HashSet<CreditTransactionCode>();
            this.PORequests = new HashSet<PORequest>();
            this.PORequestLines = new HashSet<PORequestLine>();
            this.APDocumentLines = new HashSet<APDocumentLine>();
            this.PMDivisions = new HashSet<ProjectDivision>();
            this.Equipments = new HashSet<Equipment>();
            this.Users = new HashSet<WPUserDivisionLink>();
            this.budHRPRs = new HashSet<HRPositionRequest>();
            this.budHRTRs = new HashSet<HRTermRequest>();
            this.budPRCRs = new HashSet<PRCrewRequest>();
            this.budAPDHs = new HashSet<APDocument>();
            this.SubDivisions = new HashSet<CompanyDivision>();
            this.budPMLMs = new HashSet<PMLocate>();
            this.budPMLRs = new HashSet<PMLocateRequest>();
            this.budPRDHs = new HashSet<PREmployeeDivision>();
        }
    
        [Key]
		public int DivisionId { get; set; }
        public string Description { get; set; }
        public byte HQCo { get; set; }
        public bool IsActive { get; set; }
        public byte PRCo { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<byte> BidEstimatePRCo { get; set; }
        public Nullable<int> BidEstimateEmpId { get; set; }
        public Nullable<byte> GeneralManagerPRCo { get; set; }
        public Nullable<int> GeneralManagerId { get; set; }
        public Nullable<byte> SalesManagerPRCo { get; set; }
        public Nullable<int> SalesManagerId { get; set; }
        public Nullable<int> ParentDivisionId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public byte HRCo { get; set; }
        public byte CMCo { get; set; }
        public byte GLCo { get; set; }
        public byte EMCo { get; set; }
        public byte APCo { get; set; }
        public byte ARCo { get; set; }
        public byte POCo { get; set; }
        public byte JCCo { get; set; }
        public byte DTCo { get; set; }
        public Nullable<int> JobStartId { get; set; }
    
        public virtual HQCompanyParm HQCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> PREmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditTransactionCode> CMTransactionCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORequest> PORequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORequestLine> PORequestLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APDocumentLine> APDocumentLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDivision> PMDivisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WPUserDivisionLink> Users { get; set; }
        public virtual Employee DivisionManger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionRequest> budHRPRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRTermRequest> budHRTRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRCrewRequest> budPRCRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APDocument> budAPDHs { get; set; }
        public virtual Employee BidManager { get; set; }
        public virtual Employee GeneralManager { get; set; }
        public virtual Employee SalesManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyDivision> SubDivisions { get; set; }
        public virtual CompanyDivision ParentDivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMLocate> budPMLMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMLocateRequest> budPMLRs { get; set; }
        public virtual HQOffice Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREmployeeDivision> budPRDHs { get; set; }
    }
}
