//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class CustomerContact
    {
        [Key]
		public byte CustGroupId { get; set; }
        [Key]
		public int CustomerId { get; set; }
        [Key]
		public int SeqId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
