//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class DailyEquipment
    {
        [Key]
		public byte DTCo { get; set; }
        [Key]
		public int TicketId { get; set; }
        [Key]
		public int LineNum { get; set; }
        public Nullable<System.DateTime> tWorkDate { get; set; }
        public string EquipmentId { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> ValueAdj { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string AdjustedBy { get; set; }
        public Nullable<System.DateTime> AdjustedOn { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
    
        public virtual DailyTicket DailyTicket { get; set; }
        public virtual WebUser AdjustedUser { get; set; }
        public virtual WebUser ModifiedUser { get; set; }
        public virtual Calendar Calendar { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
