//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class DNU_DailyJobTask
    {
        [Key]
		public byte DTCo { get; set; }
        [Key]
		public int TicketId { get; set; }
        [Key]
		public int LineNum { get; set; }
        [Key]
		public int SeqId { get; set; }
        public Nullable<System.DateTime> tWorkDate { get; set; }
        public string JobId { get; set; }
        public string PhaseId { get; set; }
        public Nullable<byte> CostTypeId { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> ValueAdj { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string AdjustedBy { get; set; }
        public Nullable<System.DateTime> AdjustedOn { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public Nullable<byte> PhaseGroupId { get; set; }
        public string BudgetCodeId { get; set; }
        public string ParentPhaseId { get; set; }
        public string ParentBudgetCodeId { get; set; }
        public Nullable<int> GanttId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> PassId { get; set; }
        public Nullable<byte> JCCo { get; set; }
    
        public virtual CostType CostType { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobPhase JobPhase { get; set; }
        public virtual Calendar Calendar { get; set; }
        public virtual WebUser AdjustedUser { get; set; }
        public virtual WebUser ModifiedUser { get; set; }
        public virtual DailyTicket DailyTicket { get; set; }
        public virtual ProjectBudgetCode BudgetCode { get; set; }
        public virtual JobPhaseCost JobPhaseCost { get; set; }
        public virtual ProjectBudgetCode ParentBudgetCode { get; set; }
        public virtual PMProjectGanttTask ProjectGanttTask { get; set; }
    }
}
