//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeLeave()
        {
            this.Entries = new HashSet<LeaveEntry>();
        }
    
        [Key]
		public byte PRCo { get; set; }
        [Key]
		public int EmployeeId { get; set; }
        [Key]
		public string LeaveCodeId { get; set; }
        public System.DateTime EligibleDate { get; set; }
        public Nullable<decimal> FixedUnits { get; set; }
        public string FixedFreq { get; set; }
        public string Cap1Freq { get; set; }
        public Nullable<decimal> Cap1Max { get; set; }
        public decimal Cap1Accum { get; set; }
        public Nullable<System.DateTime> Cap1Date { get; set; }
        public string Cap2Freq { get; set; }
        public Nullable<decimal> Cap2Max { get; set; }
        public decimal Cap2Accum { get; set; }
        public Nullable<System.DateTime> Cap2Date { get; set; }
        public string AvailBalFreq { get; set; }
        public Nullable<decimal> AvailBalMax { get; set; }
        public Nullable<decimal> CarryOver { get; set; }
        public decimal AvailBal { get; set; }
        public Nullable<System.DateTime> AvailBalDate { get; set; }
        public Nullable<System.DateTime> InUseMth { get; set; }
        public Nullable<int> InUseBatchId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string NegLeaveBalWarn { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LeaveCode LeaveCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveEntry> Entries { get; set; }
    }
}
