//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class EmploymentHistory
    {
        [Key]
		public byte HRCo { get; set; }
        [Key]
		public int HRRef { get; set; }
        public System.DateTime DateChanged { get; set; }
        [Key]
		public short Seq { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> ExpReturnDate { get; set; }
        public string Supervisor { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string Type { get; set; }
        public long KeyID { get; set; }
    
        public virtual HRResource Resource { get; set; }
    }
}
