//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class EMRevCodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMRevCodes()
        {
            this.Batch = new HashSet<EMBatchUsage>();
            this.Equipments = new HashSet<Equipment>();
            this.EquipmentRevCodes = new HashSet<Equipment>();
            this.budDTEUs = new HashSet<DailyEquipmentUsage>();
        }
    
        [Key]
		public byte EMGroup { get; set; }
        [Key]
		public string RevCode { get; set; }
        public string Description { get; set; }
        public string Basis { get; set; }
        public string WorkUM { get; set; }
        public string TimeUM { get; set; }
        public decimal HrsPerTimeUM { get; set; }
        public string UpdateHourMeter { get; set; }
        public string Notes { get; set; }
        public string HaulBased { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string MonthlyRevCodeYN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMBatchUsage> Batch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> EquipmentRevCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEquipmentUsage> budDTEUs { get; set; }
        public virtual HQGroup bHQGP { get; set; }
    }
}
