//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class EMServiceCategoryLink
    {
        [Key]
		public byte EMCo { get; set; }
        [Key]
		public int LinkId { get; set; }
        public string CategoryId { get; set; }
        public Nullable<int> ServiceItemId { get; set; }
    
        public virtual EquipmentCategory Category { get; set; }
        public virtual EMServiceItem ServiceItem { get; set; }
    }
}
