//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class EMWorkOrderStatusCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMWorkOrderStatusCode()
        {
            this.Item = new HashSet<EMWorkOrderItem>();
            this.EMCompanies = new HashSet<EMCompanyParm>();
        }
    
        [Key]
		public byte EMGroupId { get; set; }
        [Key]
		public string StatusCodeId { get; set; }
        public string Description { get; set; }
        public string StatusType { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMWorkOrderItem> Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMCompanyParm> EMCompanies { get; set; }
        public virtual EMCompanyParm EMCompany { get; set; }
        public virtual HQGroup bHQGP { get; set; }
    }
}
