//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class GroundDensity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroundDensity()
        {
            this.budBDBLs = new HashSet<BidBoreLinePass>();
            this.budBDBBs = new HashSet<BidBoreLine>();
            this.budBDIPs = new HashSet<BidBoreLineCostItemPhase>();
            this.budBDBIs = new HashSet<BidBoreLineCostItem>();
            this.budBDBRs = new HashSet<BidPackageProductionRate>();
            this.budBDBDs = new HashSet<BidPackage>();
        }
    
        [Key]
		public byte Co { get; set; }
        [Key]
		public int GroundDensityId { get; set; }
        public string Description { get; set; }
        public Nullable<int> MinPSI { get; set; }
        public Nullable<int> MaxPSI { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLinePass> budBDBLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLine> budBDBBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLineCostItemPhase> budBDIPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLineCostItem> budBDBIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackageProductionRate> budBDBRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackage> budBDBDs { get; set; }
        public virtual HQCompanyParm bHQCO { get; set; }
    }
}
