//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HQCompanyParm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HQCompanyParm()
        {
            this.Batches = new HashSet<Batch>();
            this.DailyPayrollEntries = new HashSet<DEL_DailyPayrollEntry>();
            this.PayrollTempHours = new HashSet<DTPayrollHour>();
            this.PayrollTempPerdiems = new HashSet<DTPayrollPerdiem>();
            this.Bids = new HashSet<Bid>();
            this.ProjectBudgets = new HashSet<ProjectBudgetCode>();
            this.DailyTickets = new HashSet<DailyTicket>();
            this.PayrollEntries = new HashSet<PayrollEntry>();
            this.budBDGDs = new HashSet<GroundDensity>();
            this.XXX_Attachments = new HashSet<HQAttachmentFile>();
            this.budWPFHs = new HashSet<Forum>();
            this.budAPDHs = new HashSet<APDocument>();
            this.APTransactions = new HashSet<APBatchHeader>();
            this.GLParameters = new HashSet<GLParameter>();
            this.budDTEUs = new HashSet<DailyEquipmentUsage>();
            this.ARTransactions = new HashSet<ARTran>();
            this.WorkFlows = new HashSet<WorkFlow>();
            this.CreditImports = new HashSet<CreditImport>();
            this.MerchantCategories = new HashSet<CreditMerchantCategory>();
            this.MerchantGroups = new HashSet<CreditMerchantGroup>();
            this.Merchants = new HashSet<CreditMerchant>();
            this.JobIndustries = new HashSet<JCIndustry>();
            this.JobMarkets = new HashSet<JCMarket>();
            this.XXX_Customers = new HashSet<Customer>();
            this.PMTempProjects = new HashSet<PMTempJob>();
            this.ServiceItems = new HashSet<EMServiceItem>();
            this.BatchTableControls = new HashSet<BatchTableControl>();
            this.Divisions = new HashSet<CompanyDivision>();
            this.XXX_EarnCodes = new HashSet<EarnCode>();
            this.XXX_JobContracts = new HashSet<JCContract>();
            this.XXX_Jobs = new HashSet<Job>();
            this.XXX_PurchaseOrders = new HashSet<PurchaseOrder>();
            this.XXX_Equipments = new HashSet<Equipment>();
            this.XXX_Resources = new HashSet<HRResource>();
            this.XXX_PORequests = new HashSet<PORequest>();
            this.XXX_LeaveRequests = new HashSet<LeaveRequest>();
            this.budSMRHs = new HashSet<SMRequest>();
            this.HQAttatchments = new HashSet<HQAttachment>();
        }
    
        [Key]
		public byte HQCo { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Address2 { get; set; }
        public string FedTaxId { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<byte> VendorGroupId { get; set; }
        public Nullable<byte> MatlGroupId { get; set; }
        public Nullable<byte> PhaseGroupId { get; set; }
        public Nullable<byte> CustGroupId { get; set; }
        public Nullable<byte> TaxGroupId { get; set; }
        public Nullable<byte> EMGroupId { get; set; }
        public Nullable<int> Vendor { get; set; }
        public Nullable<int> Customer { get; set; }
        public string AuditCoParams { get; set; }
        public string AuditTax { get; set; }
        public string AuditMatl { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<byte> ShopGroupId { get; set; }
        public string STEmpId { get; set; }
        public string MenuImage { get; set; }
        public long KeyID { get; set; }
        public string Country { get; set; }
        public string DefaultCountry { get; set; }
        public byte ReportDateFormat { get; set; }
        public Nullable<byte> ContactGroup { get; set; }
        public string AuditContact { get; set; }
        public Nullable<int> DFId { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> MaskId { get; set; }
        public string QuebecEmployerID { get; set; }
        public string CompanyLabel { get; set; }
        public Nullable<byte> APCo { get; set; }
        public Nullable<byte> ARCo { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public Nullable<byte> POCo { get; set; }
        public Nullable<byte> GLCo { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public Nullable<byte> HRCo { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public Nullable<byte> DTCo { get; set; }
        public Nullable<int> udNextAttchmentId { get; set; }
        public Nullable<int> udNextWorkFlowId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEL_DailyPayrollEntry> DailyPayrollEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTPayrollHour> PayrollTempHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTPayrollPerdiem> PayrollTempPerdiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudgetCode> ProjectBudgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyTicket> DailyTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollEntry> PayrollEntries { get; set; }
        public virtual JCCompanyParm JCCompanyParm { get; set; }
        public virtual PRCompanyParm dbPRCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroundDensity> budBDGDs { get; set; }
        public virtual POCompanyParm POCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HQAttachmentFile> XXX_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Forum> budWPFHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APDocument> budAPDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APBatchHeader> APTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLParameter> GLParameters { get; set; }
        public virtual EMCompanyParm EMCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEquipmentUsage> budDTEUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTran> ARTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkFlow> WorkFlows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditImport> CreditImports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditMerchantCategory> MerchantCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditMerchantGroup> MerchantGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditMerchant> Merchants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JCIndustry> JobIndustries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JCMarket> JobMarkets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> XXX_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMTempJob> PMTempProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMServiceItem> ServiceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchTableControl> BatchTableControls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyDivision> Divisions { get; set; }
        public virtual PMCompanyParm PMCompanyParm { get; set; }
        public virtual HQGroup PhaseGroup { get; set; }
        public virtual APCompanyParm APCompanyParm { get; set; }
        public virtual HQGroup VendorGroup { get; set; }
        public virtual HRCompanyParm HRCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EarnCode> XXX_EarnCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JCContract> XXX_JobContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> XXX_Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> XXX_PurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> XXX_Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRResource> XXX_Resources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORequest> XXX_PORequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRequest> XXX_LeaveRequests { get; set; }
        public virtual DTCompanyParm DTCompanyParm { get; set; }
        public virtual HQGroup TaxGroup { get; set; }
        public virtual HQGroup EMGroup { get; set; }
        public virtual HQGroup CustGroup { get; set; }
        public virtual BDCompanyParm BDCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMRequest> budSMRHs { get; set; }
        public virtual PRCompanyParm PRCompanyParmLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HQAttachment> HQAttatchments { get; set; }
        public virtual HQGroup MatlGroup { get; set; }
    }
}
