//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HQMaterial
    {
        [Key]
		public byte MatlGroupId { get; set; }
        [Key]
		public string MaterialId { get; set; }
        public string CategoryId { get; set; }
        public string Description { get; set; }
        public string StdUM { get; set; }
        public decimal Cost { get; set; }
        public string CostECM { get; set; }
        public decimal Price { get; set; }
        public string PriceECM { get; set; }
        public string PayDiscType { get; set; }
        public string PurchaseUM { get; set; }
        public string SalesUM { get; set; }
        public Nullable<decimal> WeightConv { get; set; }
        public string Stocked { get; set; }
        public string Taxable { get; set; }
        public string MatlPhase { get; set; }
        public Nullable<byte> MatlJCCostType { get; set; }
        public string HaulPhase { get; set; }
        public Nullable<byte> HaulJCCostType { get; set; }
        public string HaulCode { get; set; }
        public string Active { get; set; }
        public string PriceServiceId { get; set; }
        public string Type { get; set; }
        public string Notes { get; set; }
        public decimal PayDiscRate { get; set; }
        public string MetricUM { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string EMCostCode { get; set; }
        public Nullable<byte> EMCostType { get; set; }
    
        public virtual HQMaterialCategory Category { get; set; }
    }
}
