//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HRCode
    {
        [Key]
		public byte HRCo { get; set; }
        [Key]
		public string CodeId { get; set; }
        [Key]
		public string TypeId { get; set; }
        public string Description { get; set; }
        public string SafetyYN { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<short> CertPeriod { get; set; }
        public long KeyID { get; set; }
        public string PTOTypeYN { get; set; }
        public string PRLeaveCode { get; set; }
        public string PortalTermCode { get; set; }
    }
}
