//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HRCompanyParm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRCompanyParm()
        {
            this.HRResources = new HashSet<HRResource>();
            this.HRPositionRequests = new HashSet<HRPositionRequest>();
            this.HRTermRequests = new HashSet<HRTermRequest>();
            this.HRBenefitCodes = new HashSet<HRBenefitCode>();
            this.HRBenefitGroups = new HashSet<HRBenefitGroup>();
            this.HRPositions = new HashSet<HRPosition>();
            this.HRCompanyAssets = new HashSet<HRCompanyAsset>();
        }
    
        [Key]
		public byte HRCo { get; set; }
        public byte PRCo { get; set; }
        public string DependHistYN { get; set; }
        public string DependHistCode { get; set; }
        public string BenefitHistYN { get; set; }
        public string BenefitHistCode { get; set; }
        public string SalaryHistYN { get; set; }
        public string SalaryHistCode { get; set; }
        public string ReviewHistYN { get; set; }
        public string ReviewHistCode { get; set; }
        public string TrainHistYN { get; set; }
        public string TrainHistCode { get; set; }
        public string SkillsHistYN { get; set; }
        public string SkillsHistCode { get; set; }
        public string RewardHistYN { get; set; }
        public string RewardHistCode { get; set; }
        public string DisciplineHistYN { get; set; }
        public string DisciplineHistCode { get; set; }
        public string GrievHistYN { get; set; }
        public string GrievanceHistCode { get; set; }
        public string AccidentHistYN { get; set; }
        public string AccidentHistCode { get; set; }
        public string DrugHistYN { get; set; }
        public string DrugHistCode { get; set; }
        public Nullable<byte> FMLAReqMonths { get; set; }
        public decimal FMLAReqHours { get; set; }
        public string AuditCoYN { get; set; }
        public string AuditResourceYN { get; set; }
        public string AuditBenefitsYN { get; set; }
        public string AuditSalaryHistYN { get; set; }
        public string AuditReviewYN { get; set; }
        public string AuditSkillsYN { get; set; }
        public string AuditTrainingYN { get; set; }
        public string AuditRewardsYN { get; set; }
        public string AuditDisciplineYN { get; set; }
        public string AuditGrievanceYN { get; set; }
        public string AuditAccidentsYN { get; set; }
        public string AuditPositionsYN { get; set; }
        public string AuditEmplHistYN { get; set; }
        public string AuditDrugYN { get; set; }
        public string UpdateNameYN { get; set; }
        public string UpdateAddressYN { get; set; }
        public string UpdateHireDateYN { get; set; }
        public string UpdateActiveYN { get; set; }
        public string UpdatePRGroupYN { get; set; }
        public string UpdateTimecardYN { get; set; }
        public string UpdateW4YN { get; set; }
        public string UpdateSalaryYN { get; set; }
        public string UpdateBenefitsYN { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string UpdateOccupCatYN { get; set; }
        public string AuditAssetYN { get; set; }
        public string UpdateSSNYN { get; set; }
        public long KeyID { get; set; }
        public string AttachBatchReportsYN { get; set; }
        public string AuditPTOYN { get; set; }
        public string InitDrugTestStatus { get; set; }
    
        public virtual HQCompanyParm HQCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRResource> HRResources { get; set; }
        public virtual PRCompanyParm PRCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionRequest> HRPositionRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRTermRequest> HRTermRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRBenefitCode> HRBenefitCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRBenefitGroup> HRBenefitGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPosition> HRPositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRCompanyAsset> HRCompanyAssets { get; set; }
    }
}
