//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HRDrugTest
    {
        [Key]
		public byte HRCo { get; set; }
        [Key]
		public int HRRef { get; set; }
        [Key]
		public System.DateTime Date { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string Job { get; set; }
        public string Location { get; set; }
        public string Tester { get; set; }
        public string TestType { get; set; }
        public string TestStatus { get; set; }
        public string Results { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<int> HistSeq { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
    
        public virtual HRResource HRResource { get; set; }
    }
}
