//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HRPositionRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRPositionRequest()
        {
            this.TermSources = new HashSet<HRTermRequest>();
            this.WAApplicants = new HashSet<HRPositionApplicant>();
            this.AssignedTasks = new HashSet<HRPositionRequestTask>();
        }
    
        [Key]
		public byte HRCo { get; set; }
        [Key]
		public int RequestId { get; set; }
        public string PositionCodeId { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public string tForCrewId { get; set; }
        public Nullable<int> tPriorEmployeeId { get; set; }
        public Nullable<int> tNewEmployeeId { get; set; }
        public string RequestedBy { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public string Comments { get; set; }
        public int tStatusId { get; set; }
        public int WorkFlowId { get; set; }
        public Nullable<int> tWPDivisionId { get; set; }
        public Nullable<bool> tCreateCrew { get; set; }
        public Nullable<int> PRCrewRequestId { get; set; }
        public Nullable<int> tWAApplicantId { get; set; }
        public Nullable<int> tWAApplicationId { get; set; }
    
        public virtual HRCompanyParm HRCompanyParm { get; set; }
        public virtual HRPosition HRPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRTermRequest> TermSources { get; set; }
        public virtual WorkFlow WorkFlow { get; set; }
        public virtual WebUser RequestedUser { get; set; }
        public virtual Crew ForCrew { get; set; }
        public virtual Employee NewPREmployee { get; set; }
        public virtual Employee PriorPREmployee { get; set; }
        public virtual CompanyDivision WPDivision { get; set; }
        public virtual PRCrewRequest PRCrewRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionApplicant> WAApplicants { get; set; }
        public virtual WebApplication WAApplication { get; set; }
        public virtual WebApplicant WAApplicant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionRequestTask> AssignedTasks { get; set; }
    }
}
