//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HRResourceBenefit
    {
        [Key]
		public byte HRCo { get; set; }
        [Key]
		public int HRRef { get; set; }
        [Key]
		public string BenefitCodeId { get; set; }
        [Key]
		public int DependentSeq { get; set; }
        public Nullable<System.DateTime> EligDate { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public string ActiveYN { get; set; }
        public Nullable<System.DateTime> EffectDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ReinstateYN { get; set; }
        public Nullable<System.DateTime> ReinstateDate { get; set; }
        public string SmokerYN { get; set; }
        public string ID { get; set; }
        public Nullable<decimal> EmployerCost { get; set; }
        public Nullable<int> HistSeq { get; set; }
        public string UpdatedYN { get; set; }
        public string Notes { get; set; }
        public string CafePlanYN { get; set; }
        public Nullable<decimal> CafePlanAmt { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> InUseBatchId { get; set; }
        public Nullable<System.DateTime> InUseMth { get; set; }
        public string Ben1 { get; set; }
        public string Rel1 { get; set; }
        public string Ben2 { get; set; }
        public string Rel2 { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string SeriesTwoCode { get; set; }
    
        public virtual HRResource bHRRM { get; set; }
        public virtual HRBenefitCode bHRBC { get; set; }
    }
}
