//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HRSalaryHistory
    {
        [Key]
		public byte HRCo { get; set; }
        [Key]
		public int HRRef { get; set; }
        [Key]
		public System.DateTime EffectiveDate { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> OldSalary { get; set; }
        public Nullable<decimal> NewSalary { get; set; }
        public string NewPositionCode { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public string UpdatedYN { get; set; }
        public Nullable<int> HistSeq { get; set; }
        public string CalcYN { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> InUseBatchId { get; set; }
        public Nullable<System.DateTime> InUseMth { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
    
        public virtual HRResource HREmployee { get; set; }
    }
}
