//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HRTermRequest
    {
        [Key]
		public byte HRCo { get; set; }
        [Key]
		public int RequestId { get; set; }
        public Nullable<int> tHRRef { get; set; }
        public string Comments { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public string RequestedBy { get; set; }
        public int tStatusId { get; set; }
        public string PRComments { get; set; }
        public string HRComments { get; set; }
        public string TermCodeId { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> PayrollEndDate { get; set; }
        public int WorkFlowId { get; set; }
        public Nullable<bool> tIsOpenRequest { get; set; }
        public Nullable<byte> PositionHRCo { get; set; }
        public Nullable<int> PositionRequestId { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<int> tWPDivisionId { get; set; }
    
        public virtual HRCompanyParm HRCompanyParm { get; set; }
        public virtual HRResource HRResource { get; set; }
        public virtual HRPositionRequest PositionRequest { get; set; }
        public virtual WorkFlow WorkFlow { get; set; }
        public virtual WebUser RequestedUser { get; set; }
        public virtual HQAttachment HQAttachment { get; set; }
        public virtual CompanyDivision WPDivision { get; set; }
    }
}
