//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class ImportTexTag
    {
        [Key]
		public byte CMCo { get; set; }
        [Key]
		public int ImportId { get; set; }
        [Key]
		public int ImportLineId { get; set; }
        public long TransactionNumber { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Location { get; set; }
        public string TagNumber { get; set; }
        public string TransType { get; set; }
        public decimal Amount { get; set; }
        public string TransDateStr { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public string EMEquipmentId { get; set; }
        public bool IsError { get; set; }
        public string AmountStr { get; set; }
    
        public virtual CreditImport Import { get; set; }
        public virtual Equipment EMEquipment { get; set; }
    }
}
