//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class JobPhaseTrack
    {
        [Key]
		public byte JCCo { get; set; }
        [Key]
		public string JobId { get; set; }
        [Key]
		public byte PhaseGroupId { get; set; }
        [Key]
		public string PhaseId { get; set; }
        [Key]
		public byte PassId { get; set; }
        public string PlannedBudgetCodeId { get; set; }
        public Nullable<System.DateTime> ProjectedStartDate { get; set; }
        public Nullable<decimal> ProjectedDuration { get; set; }
        public string tActualBudgetCodeId { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<decimal> ActualDuration { get; set; }
        public Nullable<decimal> tPercentCompletion { get; set; }
        public Nullable<int> SortId { get; set; }
        public Nullable<decimal> ActualUnits { get; set; }
        public Nullable<int> GanttId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<System.DateTime> RemainingStartDate { get; set; }
        public Nullable<decimal> RemainingDuration { get; set; }
        public Nullable<decimal> RemainingUnits { get; set; }
        public Nullable<int> RemainingGanttId { get; set; }
        public Nullable<int> RemainingTaskId { get; set; }
        public Nullable<int> ActualGanttId { get; set; }
        public Nullable<int> ActualTaskId { get; set; }
        public Nullable<decimal> ManualUnits { get; set; }
        public Nullable<decimal> ManualPercentComplete { get; set; }
        public Nullable<bool> ManualIsComplete { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<bool> IsMilestone { get; set; }
    
        public virtual JobPhase JobPhase { get; set; }
        public virtual ProjectBudgetCode ActualBudgetCode { get; set; }
        public virtual ProjectBudgetCode PlannedBudgetCode { get; set; }
        public virtual Job Job { get; set; }
        public virtual PMProjectGanttTask ProjectGanttTask { get; set; }
        public virtual PMProjectGanttTask RemainingProjectGanttTask { get; set; }
        public virtual PMProjectGanttTask ActualProjectGanttTask { get; set; }
    }
}
