//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class LeaveRequestLine
    {
        [Key]
		public byte PRCo { get; set; }
        [Key]
		public int RequestId { get; set; }
        [Key]
		public int LineId { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string LeaveCodeId { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> LineNum { get; set; }
        public Nullable<System.DateTime> TicketDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LeaveRequest Request { get; set; }
        public virtual LeaveCode LeaveCode { get; set; }
        public virtual Calendar Calendar { get; set; }
    }
}
