//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PayrollEntry
    {
        [Key]
		public byte PRCo { get; set; }
        [Key]
		public byte PRGroup { get; set; }
        [Key]
		public System.DateTime PREndDate { get; set; }
        [Key]
		public int EmployeeId { get; set; }
        [Key]
		public byte PaySeq { get; set; }
        [Key]
		public short PostSeq { get; set; }
        public string Type { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string JobId { get; set; }
        public Nullable<byte> PhaseGroupId { get; set; }
        public string PhaseId { get; set; }
        public string JCDept { get; set; }
        public byte GLCo { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public string WO { get; set; }
        public Nullable<short> WOItem { get; set; }
        public string EquipmentId { get; set; }
        public Nullable<byte> EMGroupId { get; set; }
        public string CostCode { get; set; }
        public string CompType { get; set; }
        public string Component { get; set; }
        public string RevCode { get; set; }
        public Nullable<byte> EquipCType { get; set; }
        public Nullable<decimal> UsageUnits { get; set; }
        public string TaxState { get; set; }
        public string LocalCode { get; set; }
        public string UnempState { get; set; }
        public string InsState { get; set; }
        public string InsCode { get; set; }
        public string PRDept { get; set; }
        public string CrewId { get; set; }
        public string Cert { get; set; }
        public string Craft { get; set; }
        public string Class { get; set; }
        public short EarnCodeId { get; set; }
        public byte Shift { get; set; }
        public decimal Hours { get; set; }
        public decimal Rate { get; set; }
        public decimal Amt { get; set; }
        public Nullable<int> InUseBatchId { get; set; }
        public int BatchId { get; set; }
        public string Memo { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string EquipPhase { get; set; }
        public long KeyID { get; set; }
        public Nullable<byte> SMCo { get; set; }
        public Nullable<int> SMWorkOrder { get; set; }
        public Nullable<int> SMScope { get; set; }
        public string SMPayType { get; set; }
        public Nullable<short> SMCostType { get; set; }
        public Nullable<byte> SMJCCostType { get; set; }
        public Nullable<byte> SMPhaseGroup { get; set; }
        public Nullable<long> PRTBKeyID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public decimal BreakHours { get; set; }
        public string SMDepartment { get; set; }
        public Nullable<short> EquipSMCostType { get; set; }
        public Nullable<int> udTicketId { get; set; }
        public Nullable<int> udTicketLineId { get; set; }
        public Nullable<byte> udDTCo { get; set; }
    
        public virtual EarnCode EarnCode { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PayPeriod PayPeriod { get; set; }
        public virtual Calendar Calendar { get; set; }
        public virtual HQCompanyParm Company { get; set; }
        public virtual PRCompanyParm PRCompany { get; set; }
        public virtual PRDepartment PRDepartment { get; set; }
        public virtual EMCostCode EMCostCode { get; set; }
        public virtual Equipment EMEquipment { get; set; }
        public virtual Job JCJob { get; set; }
        public virtual JobPhase JCJobPhase { get; set; }
        public virtual Crew PRCrew { get; set; }
        public virtual HQGroup bHQGP { get; set; }
        public virtual HQGroup bHQGP1 { get; set; }
        public virtual DailyTicket Ticket { get; set; }
    }
}
