//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PayTerm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayTerm()
        {
            this.Vendors = new HashSet<APVendor>();
            this.Customers = new HashSet<Customer>();
        }
    
        [Key]
		public string PayTerms { get; set; }
        public string Description { get; set; }
        public byte DiscOpt { get; set; }
        public Nullable<byte> DaysTillDisc { get; set; }
        public Nullable<byte> DiscDay { get; set; }
        public byte DueOpt { get; set; }
        public Nullable<byte> DaysTillDue { get; set; }
        public Nullable<byte> DueDay { get; set; }
        public Nullable<byte> CutOffDay { get; set; }
        public decimal DiscRate { get; set; }
        public string MatlDisc { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public byte RollAheadTwoMonths { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APVendor> Vendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
