//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PMCompanyParm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMCompanyParm()
        {
            this.BudgetCodes = new HashSet<ProjectBudgetCode>();
            this.bPMEDs = new HashSet<ProjectBudgetLine>();
            this.Budgets = new HashSet<ProjectBudget>();
        }
    
        [Key]
		public byte PMCo { get; set; }
        public string APInUse { get; set; }
        public string SLInUse { get; set; }
        public string POInUse { get; set; }
        public Nullable<byte> APCo { get; set; }
        public string INInUse { get; set; }
        public Nullable<byte> INCo { get; set; }
        public string MSInUse { get; set; }
        public Nullable<byte> MSCo { get; set; }
        public string PRInUse { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public string EMInUse { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public Nullable<byte> PhaseGroup { get; set; }
        public Nullable<byte> SLCostType { get; set; }
        public Nullable<byte> MtlCostType { get; set; }
        public string SigPartJob { get; set; }
        public Nullable<short> SigCharsPO { get; set; }
        public Nullable<short> SigCharsMO { get; set; }
        public Nullable<short> SigCharsSL { get; set; }
        public string SLNo { get; set; }
        public Nullable<byte> SLCharsProject { get; set; }
        public Nullable<byte> SLCharsVendor { get; set; }
        public string PONo { get; set; }
        public Nullable<byte> POCharsProject { get; set; }
        public Nullable<byte> POCharsVendor { get; set; }
        public string MONo { get; set; }
        public Nullable<byte> MOCharsProject { get; set; }
        public string PhaseDescYN { get; set; }
        public Nullable<byte> VendorGroup { get; set; }
        public Nullable<int> OurFirm { get; set; }
        public Nullable<byte> SLSeqLen { get; set; }
        public Nullable<byte> POSeqLen { get; set; }
        public Nullable<byte> MOSeqLen { get; set; }
        public byte SLCT1Option { get; set; }
        public Nullable<byte> SLCostType2 { get; set; }
        public byte MTCT1Option { get; set; }
        public string POSigPartJob { get; set; }
        public string MOGroupByLoc { get; set; }
        public string BeginStatus { get; set; }
        public string FinalStatus { get; set; }
        public string APVendUpdYN { get; set; }
        public string DocTrackView { get; set; }
        public string RQInUse { get; set; }
        public string POCreate { get; set; }
        public string MOCreate { get; set; }
        public Nullable<short> SLStartSeq { get; set; }
        public Nullable<short> POStartSeq { get; set; }
        public Nullable<short> MOStartSeq { get; set; }
        public Nullable<byte> ShowCostType1 { get; set; }
        public Nullable<byte> ShowCostType2 { get; set; }
        public Nullable<byte> ShowCostType3 { get; set; }
        public Nullable<byte> ShowCostType4 { get; set; }
        public Nullable<byte> ShowCostType5 { get; set; }
        public Nullable<byte> ShowCostType6 { get; set; }
        public Nullable<byte> ShowCostType7 { get; set; }
        public Nullable<byte> ShowCostType8 { get; set; }
        public Nullable<byte> ShowCostType9 { get; set; }
        public Nullable<byte> ShowCostType10 { get; set; }
        public string FaxServerName { get; set; }
        public string DocHistACO { get; set; }
        public string DocHistDrawing { get; set; }
        public string DocHistInspect { get; set; }
        public string DocHistOtherDoc { get; set; }
        public string DocHistPCO { get; set; }
        public string DocHistPunchList { get; set; }
        public string DocHistRFI { get; set; }
        public string DocHistRFQ { get; set; }
        public string DocHistSubmittal { get; set; }
        public string DocHistTestLog { get; set; }
        public string DocHistTransmittal { get; set; }
        public string AuditCoParams { get; set; }
        public string AuditDailyLogs { get; set; }
        public string AuditPMCA { get; set; }
        public string AuditPMEC { get; set; }
        public string AuditPMEH { get; set; }
        public string AuditPMFM { get; set; }
        public string AuditPMIM { get; set; }
        public string AuditPMMF { get; set; }
        public string AuditPMMM { get; set; }
        public string AuditPMNR { get; set; }
        public string AuditPMPA { get; set; }
        public string AuditPMPC { get; set; }
        public string AuditPMPF { get; set; }
        public string AuditPMPL { get; set; }
        public string AuditPMPM { get; set; }
        public string AuditPMPN { get; set; }
        public string AuditPMSL { get; set; }
        public string AuditPMTH { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string UseApprSubCo { get; set; }
        public string AttachBatchReportsYN { get; set; }
        public string MatlPhaseDesc { get; set; }
        public string POAddOrigOpen { get; set; }
        public string POAddChgOpen { get; set; }
        public Nullable<byte> MatlCostType2 { get; set; }
        public string SLItemCOAutoAdd { get; set; }
        public string SLItemCOManual { get; set; }
        public string DocHistSubCO { get; set; }
        public string RFIStatus { get; set; }
        public string DocHistPOCONum { get; set; }
        public string LockDownACOItems { get; set; }
        public Nullable<int> SubmittalReviewDaysResponsibleFirm { get; set; }
        public Nullable<int> SubmittalReviewDaysApprovingFirm { get; set; }
        public Nullable<int> SubmittalReviewDaysRequestingFirm { get; set; }
        public string DocHistSubmittalRegister { get; set; }
        public string ProjMethod { get; set; }
        public decimal ProjMinPct { get; set; }
        public string ProjInactivePhases { get; set; }
        public string ProjPostForecast { get; set; }
        public string ProjJobInMultiBatch { get; set; }
        public string ProjResDetOpt { get; set; }
        public string ProjRemainUCOpt { get; set; }
        public string ProjPercent { get; set; }
        public string ProjOverUnder { get; set; }
        public string ProjRemain { get; set; }
        public string ProjSpreadOption { get; set; }
        public string RevProjOpt { get; set; }
        public string VFETemplate { get; set; }
        public string ProjRemainUnitsOption { get; set; }
        public string PCODetailNotesCopySUBCO { get; set; }
        public string PCODetailNotesCopyPOCO { get; set; }
        public Nullable<int> udNextGanttId { get; set; }
    
        public virtual HQCompanyParm HQCompanyParm { get; set; }
        public virtual JCCompanyParm JCCompanyParm { get; set; }
        public virtual CostType bJCCT { get; set; }
        public virtual CostType bJCCT1 { get; set; }
        public virtual CostType bJCCT2 { get; set; }
        public virtual Firm bPMFM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudgetCode> BudgetCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudgetLine> bPMEDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudget> Budgets { get; set; }
    }
}
