//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PMLocate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMLocate()
        {
            this.Assignments = new HashSet<PMLocateAssignment>();
            this.Sequences = new HashSet<PMLocateSequence>();
        }
    
        [Key]
		public int LocateId { get; set; }
        public int RequestId { get; set; }
        public string StateId { get; set; }
        public string tDescription { get; set; }
        public int tStatusId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string Comments { get; set; }
        public Nullable<byte> BDCo { get; set; }
        public Nullable<int> tBidId { get; set; }
        public Nullable<int> FilterPackageId { get; set; }
        public Nullable<int> FilterBoreId { get; set; }
        public Nullable<byte> FilterJCCo { get; set; }
        public string FilterJobId { get; set; }
        public Nullable<int> WorkFlowId { get; set; }
        public Nullable<byte> HQCo { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<decimal> GPSLong { get; set; }
        public Nullable<decimal> GPSLat { get; set; }
        public string tGPS { get; set; }
        public Nullable<System.DateTime> AnticipatedStartDate { get; set; }
        public string RequestedBy { get; set; }
        public System.DateTime RequestedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> MapSetId { get; set; }
        public Nullable<byte> VendorGroupId { get; set; }
        public Nullable<int> FirmNumber { get; set; }
        public Nullable<int> TempImportId { get; set; }
        public Nullable<int> TempImportLineId { get; set; }
        public string tCrossStreet { get; set; }
        public string tCity { get; set; }
        public string tCounty { get; set; }
        public string Location { get; set; }
        public string PiggyBackLocateRefId { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual BidPackage BidPackage { get; set; }
        public virtual Bid Bid { get; set; }
        public virtual HQAttachment HQAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMLocateAssignment> Assignments { get; set; }
        public virtual PMLocateRequest Request { get; set; }
        public virtual CompanyDivision Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMLocateSequence> Sequences { get; set; }
        public virtual WebUser CreatedUser { get; set; }
        public virtual WebUser budWPUM1 { get; set; }
        public virtual WPMapSet WPMapSet { get; set; }
        public virtual PMLocate_Import budPMLM_Import { get; set; }
    }
}
