//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PMLocateSequence
    {
        [Key]
		public int LocateId { get; set; }
        [Key]
		public int SeqId { get; set; }
        public string StateId { get; set; }
        public string LocateRefId { get; set; }
        public Nullable<int> tStatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> DaysToExpire { get; set; }
        public Nullable<int> WorkFlowId { get; set; }
        public Nullable<byte> HQCo { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
    
        public virtual HQAttachment HQAttachment { get; set; }
        public virtual PMLocate Locate { get; set; }
    }
}
