//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PMProjectGanttTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMProjectGanttTask()
        {
            this.BidBoreLines = new HashSet<BidBoreLine>();
            this.BidBorePackages = new HashSet<BidPackage>();
            this.BidBoreLineTasks = new HashSet<BidBoreLinePass>();
            this.DailyTasks = new HashSet<DNU_DailyJobTask>();
            this.SubTasks = new HashSet<PMProjectGanttTask>();
            this.Jobs = new HashSet<Job>();
            this.JobPhases = new HashSet<JobPhaseTrack>();
            this.DailyTicket = new HashSet<DailyTicket>();
            this.Owners = new HashSet<PMProjectGantTaskOwner>();
            this.JobBudgetTasks = new HashSet<JobPhaseTrack>();
            this.PhaseActualTasks = new HashSet<JobPhaseTrack>();
            this.TaskLinkSources = new HashSet<PMProjectTaskLink>();
            this.TaskLinkTargets = new HashSet<PMProjectTaskLink>();
        }
    
        [Key]
		public byte GTCo { get; set; }
        [Key]
		public int GanttId { get; set; }
        [Key]
		public int TaskId { get; set; }
        public string TaskType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public Nullable<decimal> Progress { get; set; }
        public Nullable<int> TaskSource { get; set; }
        public string Text { get; set; }
        public long KeyID { get; set; }
        public string RenderType { get; set; }
        public Nullable<int> ConstriantType { get; set; }
        public Nullable<System.DateTime> ConstraintDate { get; set; }
        public Nullable<bool> MarkedForDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLine> BidBoreLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackage> BidBorePackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLinePass> BidBoreLineTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNU_DailyJobTask> DailyTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMProjectGanttTask> SubTasks { get; set; }
        public virtual PMProjectGanttTask ParentTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPhaseTrack> JobPhases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyTicket> DailyTicket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMProjectGantTaskOwner> Owners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPhaseTrack> JobBudgetTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPhaseTrack> PhaseActualTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMProjectTaskLink> TaskLinkSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMProjectTaskLink> TaskLinkTargets { get; set; }
    }
}
