//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class POBatchItem
    {
        [Key]
		public byte Co { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public int BatchId { get; set; }
        [Key]
		public int BatchSeq { get; set; }
        [Key]
		public short POItem { get; set; }
        public string BatchTransType { get; set; }
        public byte ItemType { get; set; }
        public byte MatlGroup { get; set; }
        public string Material { get; set; }
        public string VendMatId { get; set; }
        public string Description { get; set; }
        public string UM { get; set; }
        public string RecvYN { get; set; }
        public byte PostToCo { get; set; }
        public string Loc { get; set; }
        public string JobId { get; set; }
        public Nullable<byte> PhaseGroupId { get; set; }
        public string Phase { get; set; }
        public Nullable<byte> JCCType { get; set; }
        public string EquipmentId { get; set; }
        public string CompType { get; set; }
        public string Component { get; set; }
        public Nullable<byte> EMGroup { get; set; }
        public string CostCode { get; set; }
        public Nullable<byte> EMCType { get; set; }
        public string WO { get; set; }
        public Nullable<short> WOItem { get; set; }
        public byte GLCo { get; set; }
        public string GLAcct { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public Nullable<byte> TaxGroup { get; set; }
        public string TaxCode { get; set; }
        public Nullable<byte> TaxType { get; set; }
        public decimal OrigUnits { get; set; }
        public decimal OrigUnitCost { get; set; }
        public string OrigECM { get; set; }
        public decimal OrigCost { get; set; }
        public decimal OrigTax { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> OldItemType { get; set; }
        public Nullable<byte> OldMatlGroup { get; set; }
        public string OldMaterial { get; set; }
        public string OldVendMatId { get; set; }
        public string OldDesc { get; set; }
        public string OldUM { get; set; }
        public string OldRecvYN { get; set; }
        public Nullable<byte> OldPostToCo { get; set; }
        public string OldLoc { get; set; }
        public string OldJob { get; set; }
        public Nullable<byte> OldPhaseGroup { get; set; }
        public string OldPhase { get; set; }
        public Nullable<byte> OldJCCType { get; set; }
        public string OldEquip { get; set; }
        public string OldCompType { get; set; }
        public string OldComponent { get; set; }
        public Nullable<byte> OldEMGroup { get; set; }
        public string OldCostCode { get; set; }
        public Nullable<byte> OldEMCType { get; set; }
        public string OldWO { get; set; }
        public Nullable<short> OldWOItem { get; set; }
        public Nullable<byte> OldGLCo { get; set; }
        public string OldGLAcct { get; set; }
        public Nullable<System.DateTime> OldReqDate { get; set; }
        public Nullable<byte> OldTaxGroup { get; set; }
        public string OldTaxCode { get; set; }
        public Nullable<byte> OldTaxType { get; set; }
        public Nullable<decimal> OldOrigUnits { get; set; }
        public Nullable<decimal> OldOrigUnitCost { get; set; }
        public string OldOrigECM { get; set; }
        public Nullable<decimal> OldOrigCost { get; set; }
        public Nullable<decimal> OldOrigTax { get; set; }
        public string RequisitionNum { get; set; }
        public string OldRequisitionNum { get; set; }
        public Nullable<int> PayCategory { get; set; }
        public Nullable<int> OldPayCategory { get; set; }
        public Nullable<byte> PayType { get; set; }
        public Nullable<byte> OldPayType { get; set; }
        public Nullable<byte> INCo { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public decimal JCCmtdTax { get; set; }
        public decimal OldJCCmtdTax { get; set; }
        public Nullable<int> Supplier { get; set; }
        public Nullable<byte> SupplierGroup { get; set; }
        public decimal JCRemCmtdTax { get; set; }
        public decimal OldJCRemCmtdTax { get; set; }
        public decimal TaxRate { get; set; }
        public decimal GSTRate { get; set; }
        public decimal OldTaxRate { get; set; }
        public decimal OldGSTRate { get; set; }
        public Nullable<byte> SMCo { get; set; }
        public Nullable<int> SMWorkOrder { get; set; }
        public Nullable<int> SMScope { get; set; }
        public Nullable<byte> OldSMCo { get; set; }
        public Nullable<int> OldSMWorkOrder { get; set; }
        public Nullable<int> OldScope { get; set; }
        public Nullable<byte> SMPhaseGroup { get; set; }
        public string SMPhase { get; set; }
        public Nullable<byte> SMJCCostType { get; set; }
        public Nullable<byte> OldSMPhaseGroup { get; set; }
        public string OldSMPhase { get; set; }
        public Nullable<byte> OldSMJCCostType { get; set; }
        public string CrewId { get; set; }
        public Nullable<short> SMCostType { get; set; }
        public Nullable<short> OldSMCostType { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual CostType JobCostType { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobPhase JobPhase { get; set; }
        public virtual POBatchHeader PO { get; set; }
        public virtual EMCostCode EMCostCode { get; set; }
    }
}
