//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class POCompanyParm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POCompanyParm()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PORequests = new HashSet<PORequest>();
        }
    
        [Key]
		public byte POCo { get; set; }
        public string AutoPO { get; set; }
        public string LastPO { get; set; }
        public string CmtdDetailToJC { get; set; }
        public string AuditCoParams { get; set; }
        public string AuditPOs { get; set; }
        public string Notes { get; set; }
        public string ReceiptUpdate { get; set; }
        public string GLAccrualAcct { get; set; }
        public byte GLRecExpInterfacelvl { get; set; }
        public string GLRecExpSummaryDesc { get; set; }
        public string GLRecExpDetailDesc { get; set; }
        public byte RecJCInterfacelvl { get; set; }
        public byte RecEMInterfacelvl { get; set; }
        public byte RecINInterfacelvl { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string AuditPOCompliance { get; set; }
        public string PayTypeYN { get; set; }
        public long KeyID { get; set; }
        public string AuditPOReceipts { get; set; }
        public string AttachBatchReportsYN { get; set; }
        public string QuoteReviewer { get; set; }
        public string PurchaseReviewer { get; set; }
        public Nullable<decimal> Threshold { get; set; }
        public string ThresholdReviewer { get; set; }
        public string AutoRQ { get; set; }
        public string LastRQ { get; set; }
        public string ApprforQuote { get; set; }
        public string ApprforPurchase { get; set; }
        public string AuditRQ { get; set; }
        public string AuditReview { get; set; }
        public string AuditQuote { get; set; }
        public string ByPassTriggers { get; set; }
    
        public virtual HQCompanyParm HQCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORequest> PORequests { get; set; }
    }
}
