//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PRBatchTimeEntry
    {
        [Key]
		public byte Co { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public int BatchId { get; set; }
        [Key]
		public int BatchSeq { get; set; }
        public string BatchTransType { get; set; }
        public int EmployeeId { get; set; }
        public byte PaySeq { get; set; }
        public Nullable<short> PostSeq { get; set; }
        public string Type { get; set; }
        public short DayNum { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string tJobId { get; set; }
        public Nullable<byte> PhaseGroupId { get; set; }
        public string tPhaseId { get; set; }
        public byte GLCo { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public string WO { get; set; }
        public Nullable<short> WOItem { get; set; }
        public string tEquipmentId { get; set; }
        public Nullable<byte> EMGroupId { get; set; }
        public string tCostCodeId { get; set; }
        public string CompType { get; set; }
        public string Component { get; set; }
        public string RevCode { get; set; }
        public Nullable<byte> EquipCType { get; set; }
        public Nullable<decimal> UsageUnits { get; set; }
        public string TaxState { get; set; }
        public string LocalCode { get; set; }
        public string UnempState { get; set; }
        public string InsState { get; set; }
        public string InsCode { get; set; }
        public string PRDept { get; set; }
        public string CrewId { get; set; }
        public string Cert { get; set; }
        public string Craft { get; set; }
        public string Class { get; set; }
        public short tEarnCodeId { get; set; }
        public byte Shift { get; set; }
        public decimal Hours { get; set; }
        public decimal Rate { get; set; }
        public decimal Amt { get; set; }
        public Nullable<int> OldEmployee { get; set; }
        public Nullable<byte> OldPaySeq { get; set; }
        public Nullable<short> OldPostSeq { get; set; }
        public string OldType { get; set; }
        public Nullable<System.DateTime> OldPostDate { get; set; }
        public Nullable<byte> OldJCCo { get; set; }
        public string OldJob { get; set; }
        public Nullable<byte> OldPhaseGroup { get; set; }
        public string OldPhase { get; set; }
        public Nullable<byte> OldGLCo { get; set; }
        public Nullable<byte> OldEMCo { get; set; }
        public string OldWO { get; set; }
        public Nullable<short> OldWOItem { get; set; }
        public string OldEquipment { get; set; }
        public Nullable<byte> OldEMGroup { get; set; }
        public string OldCostCode { get; set; }
        public string OldCompType { get; set; }
        public string OldComponent { get; set; }
        public string OldRevCode { get; set; }
        public Nullable<byte> OldEquipCType { get; set; }
        public Nullable<decimal> OldUsageUnits { get; set; }
        public string OldTaxState { get; set; }
        public string OldLocalCode { get; set; }
        public string OldUnempState { get; set; }
        public string OldInsState { get; set; }
        public string OldInsCode { get; set; }
        public string OldPRDept { get; set; }
        public string OldCrew { get; set; }
        public string OldCert { get; set; }
        public string OldCraft { get; set; }
        public string OldClass { get; set; }
        public Nullable<short> OldEarnCode { get; set; }
        public Nullable<byte> OldShift { get; set; }
        public Nullable<decimal> OldHours { get; set; }
        public Nullable<decimal> OldRate { get; set; }
        public Nullable<decimal> OldAmt { get; set; }
        public string Memo { get; set; }
        public string OldMemo { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string EquipPhase { get; set; }
        public string OldEquipPhase { get; set; }
        public long KeyID { get; set; }
        public Nullable<byte> SMCo { get; set; }
        public Nullable<int> SMWorkOrder { get; set; }
        public Nullable<int> SMScope { get; set; }
        public string SMPayType { get; set; }
        public Nullable<byte> OldSMCo { get; set; }
        public Nullable<int> OldSMWorkOrder { get; set; }
        public Nullable<int> OldSMScope { get; set; }
        public string OldSMPayType { get; set; }
        public Nullable<short> SMCostType { get; set; }
        public Nullable<short> OldSMCostType { get; set; }
        public Nullable<byte> SMJCCostType { get; set; }
        public Nullable<byte> OldSMJCCostType { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public decimal BreakHours { get; set; }
        public Nullable<System.DateTime> OldStartTime { get; set; }
        public Nullable<System.DateTime> OldStopTime { get; set; }
        public Nullable<decimal> OldBreakHours { get; set; }
        public Nullable<short> EquipSMCostType { get; set; }
        public Nullable<short> OldEquipSMCostType { get; set; }
        public Nullable<int> udTicketId { get; set; }
        public Nullable<int> udTicketLineId { get; set; }
        public Nullable<byte> udDTCo { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual EarnCode EarnCode { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Calendar Calendar { get; set; }
        public virtual EMCostCode EMCostCode { get; set; }
        public virtual Equipment EMEquipment { get; set; }
        public virtual Job JCJob { get; set; }
        public virtual JobPhase JCJobPhase { get; set; }
        public virtual Crew PRCrew { get; set; }
    }
}
