//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PRCrewRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRCrewRequest()
        {
            this.HRPositionRequests = new HashSet<HRPositionRequest>();
        }
    
        [Key]
		public byte PRCo { get; set; }
        [Key]
		public int RequestId { get; set; }
        public int tStatusId { get; set; }
        public Nullable<int> tWPDivisionId { get; set; }
        public string PriorCrewId { get; set; }
        public string Comments { get; set; }
        public string Description { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public string EMCatagoryId { get; set; }
        public string RequestedBy { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public int WorkFlowId { get; set; }
    
        public virtual EquipmentCategory EMCategory { get; set; }
        public virtual PRCompanyParm PRCompany { get; set; }
        public virtual Crew PriorCrew { get; set; }
        public virtual WorkFlow WorkFlow { get; set; }
        public virtual CompanyDivision WPDivision { get; set; }
        public virtual WebUser RequestedUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionRequest> HRPositionRequests { get; set; }
    }
}
