//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PRImportBenefit
    {
        [Key]
		public byte Co { get; set; }
        [Key]
		public int ImportId { get; set; }
        [Key]
		public int ImportLineId { get; set; }
        public string EECode { get; set; }
        public string EEName { get; set; }
        public string BenefitsEligibilityProfile { get; set; }
        public string HomeAllocation { get; set; }
        public string PlanYear { get; set; }
        public string PlanName { get; set; }
        public string CoverageLevel { get; set; }
        public string BenefitStatus { get; set; }
        public Nullable<System.DateTime> CoverageStartDate { get; set; }
        public Nullable<System.DateTime> CoverageEndDate { get; set; }
        public Nullable<decimal> MonthlyPremium { get; set; }
        public Nullable<decimal> EmployerCostPerPayPeriod { get; set; }
        public Nullable<decimal> EmployeeCostPerPayPeriod { get; set; }
        public string DeductionCode { get; set; }
        public string TaxTreatment { get; set; }
        public Nullable<decimal> CurrentPayrollDeduction { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public Nullable<int> PREmployeeId { get; set; }
        public Nullable<byte> HRCo { get; set; }
        public string HRBenefitCodeId { get; set; }
        public string BenefitGroupId { get; set; }
        public Nullable<bool> IsError { get; set; }
    
        public virtual CreditImport Import { get; set; }
        public virtual Employee PREmployee { get; set; }
        public virtual HRBenefitCode HRBenefitCode { get; set; }
    }
}
