//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class ProjectBudgetLine
    {
        [Key]
		public byte PMCo { get; set; }
        [Key]
		public string ProjectId { get; set; }
        [Key]
		public string BudgetNo { get; set; }
        [Key]
		public int SeqId { get; set; }
        public string CostLevel { get; set; }
        public int GroupNo { get; set; }
        public int LineId { get; set; }
        public string BudgetCodeId { get; set; }
        public string Description { get; set; }
        public byte PhaseGroupId { get; set; }
        public string PhaseId { get; set; }
        public Nullable<byte> CostTypeId { get; set; }
        public Nullable<decimal> Units { get; set; }
        public string UM { get; set; }
        public Nullable<decimal> HrsPerUnit { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<decimal> HourCost { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> Markup { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public Nullable<decimal> BoreSize { get; set; }
        public Nullable<decimal> ProductionRate { get; set; }
    
        public virtual ProjectBudget Budget { get; set; }
        public virtual ProjectBudgetCode BudgetCode { get; set; }
        public virtual UnitofMeasure UnitofMeasure { get; set; }
        public virtual JobPhase Phase { get; set; }
        public virtual CostType CostType { get; set; }
        public virtual Job Job { get; set; }
        public virtual PMCompanyParm PMCompanyParm { get; set; }
    }
}
