//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class ProjectFirm
    {
        [Key]
		public byte PMCo { get; set; }
        [Key]
		public string ProjectId { get; set; }
        [Key]
		public int Seq { get; set; }
        public byte VendorGroupId { get; set; }
        public int FirmNumber { get; set; }
        public int ContactCode { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string PortalSiteAccess { get; set; }
        public long KeyID { get; set; }
        public string EmailOption { get; set; }
        public string InviteTo4PRequested { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Firm Firm { get; set; }
        public virtual PMContact bPMPM { get; set; }
    }
}
