//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class vAPDocument
    {
        [Key]
		public byte APCo { get; set; }
        [Key]
		public int DocId { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<byte> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewedOn { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        [Key]
		public long KeyID { get; set; }
        public string Source { get; set; }
        public string VendorName { get; set; }
        public string APRef { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public Nullable<decimal> InvTotal { get; set; }
        public string CreatedUserName { get; set; }
        [Key]
		public int SeqId { get; set; }
        public string AssignedToStr { get; set; }
        public string LastCommentBy { get; set; }
        public Nullable<byte> POCo { get; set; }
        public Nullable<byte> VendorGroupId { get; set; }
    }
}
