//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class vCMBatch
    {
        [Key]
		public byte CCCo { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public string Source { get; set; }
        [Key]
		public int BatchId { get; set; }
        [Key]
		public long BatchSeq { get; set; }
        public string Status { get; set; }
        public Nullable<int> TransCnt { get; set; }
        public Nullable<decimal> PostAmount { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public string Description { get; set; }
    }
}
