//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class vCreditMerchant
    {
        [Key]
		public byte VendGroupId { get; set; }
        [Key]
		public string MerchantId { get; set; }
        public string CategoryGroup { get; set; }
        public Nullable<int> CategoryCodeId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> MerchantCategoryCode { get; set; }
        public Nullable<bool> IsReoccurring { get; set; }
        public Nullable<bool> IsReceiptRequired { get; set; }
        public string DefaultGLAcct { get; set; }
        public string DefaultJCPhaseId { get; set; }
        public Nullable<byte> DefaultJCCType { get; set; }
        public string DefaultEMCostCodeId { get; set; }
        public Nullable<byte> DefaultEMCType { get; set; }
        public string CategoryCodeDescription { get; set; }
        public string CategoryGroupDescription { get; set; }
        public Nullable<decimal> TransTotal { get; set; }
        public Nullable<int> TransCount { get; set; }
        public string VendorName { get; set; }
        public string GroupDefaultGLAcct { get; set; }
        public string GroupDefaultJCPhaseId { get; set; }
        public Nullable<byte> GroupDefaultJCCType { get; set; }
        public string GroupDefaultEMCostCodeId { get; set; }
        public Nullable<byte> GroupDefaultEMCType { get; set; }
        public Nullable<int> CategoryDefaultVendorId { get; set; }
        public string CategoryDefaultGLAcct { get; set; }
        public string CategoryDefaultJCPhaseId { get; set; }
        public Nullable<byte> CategoryDefaultJCCType { get; set; }
        public string CategoryDefaultEMCostCodeId { get; set; }
        public Nullable<byte> CategoryDefaultEMCType { get; set; }
        public Nullable<bool> IsAPRefRequired { get; set; }
        public Nullable<byte> DefaultLineTypeId { get; set; }
    }
}
