//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class WADrivingExperience
    {
        [Key]
		public int ApplicantId { get; set; }
        [Key]
		public int ApplicationId { get; set; }
        [Key]
		public int SeqId { get; set; }
        public string TypeOfEquipment { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<long> Miliage { get; set; }
    
        public virtual WebApplication Application { get; set; }
    }
}
