//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class WebApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebApplication()
        {
            this.AppliedPositions = new HashSet<WAAppliedPosition>();
            this.DrivingExperiences = new HashSet<WADrivingExperience>();
            this.TrafficIncidents = new HashSet<WATrafficIncident>();
            this.WorkExperiences = new HashSet<WAWorkExperience>();
            this.HRPositionRequests = new HashSet<HRPositionApplicant>();
            this.HRPositionRequest = new HashSet<HRPositionRequest>();
            this.DrugTests = new HashSet<WAApplicantDrugTest>();
        }
    
        [Key]
		public int ApplicantId { get; set; }
        [Key]
		public int ApplicationId { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public int tStatusId { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string ActiveYN { get; set; }
        public Nullable<byte> HRCo { get; set; }
        public Nullable<int> HRRef { get; set; }
        public Nullable<bool> tAccidents { get; set; }
        public Nullable<bool> tCitiations { get; set; }
        public byte WFCo { get; set; }
        public Nullable<int> WorkFlowId { get; set; }
        public bool tIsActive { get; set; }
        public Nullable<int> tDeniedReasonId { get; set; }
        public Nullable<int> ForumId { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public string PRDeptId { get; set; }
        public Nullable<byte> PRGroupId { get; set; }
        public Nullable<decimal> PRHrlyRate { get; set; }
        public Nullable<decimal> PRSalaryAmt { get; set; }
        public Nullable<decimal> PRPerDeimRate { get; set; }
        public Nullable<short> PREarnCodeId { get; set; }
        public Nullable<int> PRReportsToId { get; set; }
        public Nullable<int> WPDivisionId { get; set; }
        public string PRInsStateId { get; set; }
        public string PRInsCodeId { get; set; }
        public Nullable<byte> ForumCo { get; set; }
        public string HRDotStatus { get; set; }
        public Nullable<System.Guid> WebGuid { get; set; }
    
        public virtual WebApplicant Applicant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAAppliedPosition> AppliedPositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WADrivingExperience> DrivingExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WATrafficIncident> TrafficIncidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAWorkExperience> WorkExperiences { get; set; }
        public virtual WorkFlow WorkFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionApplicant> HRPositionRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionRequest> HRPositionRequest { get; set; }
        public virtual HRResource HRResource { get; set; }
        public virtual Forum Forum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAApplicantDrugTest> DrugTests { get; set; }
        public virtual HQAttachment HQAttachment { get; set; }
    }
}
