//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class WebMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebMenu()
        {
            this.SubMenus = new HashSet<WebMenu>();
        }
    
        [Key]
		public int MenuId { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentMenuId { get; set; }
        public Nullable<int> ControllerActionId { get; set; }
        public string IconClass { get; set; }
        public string Href { get; set; }
        public int SortId { get; set; }
        public string Parameters { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebMenu> SubMenus { get; set; }
        public virtual WebMenu ParentMenu { get; set; }
        public virtual WebController Action { get; set; }
    }
}
