//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class WebUserAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebUserAccess()
        {
            this.Logs = new HashSet<WebUserLog>();
        }
    
        [Key]
		public string UserId { get; set; }
        [Key]
		public int ControllerActionId { get; set; }
        public Nullable<byte> AccessLevel { get; set; }
        public Nullable<System.DateTime> LastAccessed { get; set; }
    
        public virtual WebController ControllerAction { get; set; }
        public virtual WebUser User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebUserLog> Logs { get; set; }
    }
}
