//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class WPExcelImport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WPExcelImport()
        {
            this.Sheets = new HashSet<WPExcelSheet>();
            this.LocateImportLines = new HashSet<PMLocate_Import>();
        }
    
        [Key]
		public int ImportId { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public int ImportTypeId { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Processed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WPExcelSheet> Sheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMLocate_Import> LocateImportLines { get; set; }
    }
}
