//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class WPExcelSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WPExcelSheet()
        {
            this.LocateImports = new HashSet<PMLocate_Import>();
        }
    
        [Key]
		public int ImportId { get; set; }
        [Key]
		public int SheetId { get; set; }
        public string SheetName { get; set; }
        public byte[] JsonData { get; set; }
    
        public virtual WPExcelImport Import { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMLocate_Import> LocateImports { get; set; }
    }
}
