//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class WPUserDivisionLink
    {
        [Key]
		public string UserId { get; set; }
        [Key]
		public int DivisionId { get; set; }
        public bool Active { get; set; }
    
        public virtual CompanyDivision Division { get; set; }
        public virtual WebUser User { get; set; }
    }
}
