//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Infrastructure.ViewPointDB.Data
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class ZionImport
    {
        [Key]
		public byte CCCo { get; set; }
        [Key]
		public int ImportId { get; set; }
        [Key]
		public int ImportLineId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> StatementStartDate { get; set; }
        public Nullable<System.DateTime> StatementEndDate { get; set; }
        public Nullable<int> CardEmployeeId { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeEmail { get; set; }
        public string CardHolderFirstName { get; set; }
        public string CardHolderLastName { get; set; }
        public string TransactionReference { get; set; }
        public Nullable<int> TransLineNumber { get; set; }
        public Nullable<int> TransSequenceReference { get; set; }
        public string TransSequenceNumber { get; set; }
        public string TransactionSecondDescription { get; set; }
        public Nullable<System.DateTime> TransPostDate { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string TransactionType { get; set; }
        public string TransactionBillingCurrencyCode { get; set; }
        public Nullable<decimal> TransBillingAmount { get; set; }
        public Nullable<decimal> TransLineAmount { get; set; }
        public Nullable<decimal> TransLineTaxAmount { get; set; }
        public Nullable<int> TransStatusId { get; set; }
        public string TransactionStatusDescription { get; set; }
        public string MerchantId { get; set; }
        public string MerchantName { get; set; }
        public string MerchantAddress { get; set; }
        public string MerchantCity { get; set; }
        public string MerchantState { get; set; }
        public string MerchantZip { get; set; }
        public string MerchantCountry { get; set; }
        public string EmployeeVendorId { get; set; }
        public string TransactionReceiptFlag { get; set; }
        public string TransactionReceiptImageName { get; set; }
        public string TransactionReceiptImageReferenceId { get; set; }
        public Nullable<int> MerchantCategoryCode { get; set; }
        public string MerchantCategoryCodeDescription { get; set; }
        public string MerchantCategoryGroup { get; set; }
        public string MerchantCategoryGroupDescription { get; set; }
        public string TransactionLineItemBillNumber { get; set; }
        public string TransactionLineItemDescription { get; set; }
        public string TransactionLineItemLastItem { get; set; }
        public Nullable<decimal> TransactionLineItemTotal { get; set; }
        public string TransactionLineItemMessageIdDetail { get; set; }
        public string TransactionLineItemMessageIdSummary { get; set; }
        public string TransactionLineItemOrderDate { get; set; }
        public string TransactionLineItemProductCode { get; set; }
        public string TransactionLineItemPurchaseId { get; set; }
        public string TransactionLineItemPurchaseType { get; set; }
        public Nullable<decimal> TransactionLineItemQuantity { get; set; }
        public string TransactionLineItemServiceIdentifierDetail { get; set; }
        public string TransactionLineItemServiceIdentifierSummary { get; set; }
        public string TransactionLineItemSourceCountryCode { get; set; }
        public string TransactionLineItemSourcePostalCode { get; set; }
        public string TransactionLineItemTaxAmount { get; set; }
        public string TransactionLineItemTaxRate { get; set; }
        public string TransactionLineItemUnitofMeasure { get; set; }
        public Nullable<decimal> TransactionLineItemUnitPrice { get; set; }
        public string TransactionLineCodingJobNumber { get; set; }
        public string TransactionLineCodingTaskPhaseCode { get; set; }
        public Nullable<byte> TransactionLineCodingJobCostType { get; set; }
        public string TransactionLineCodingEquipmentNumber { get; set; }
        public string TransactionLineCodingEquipmentCostCode { get; set; }
        public Nullable<byte> TransactionLineCodingEquipmentCostType { get; set; }
        public string TransactionLineCodingGLNumber { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public Nullable<int> PREmployeeId { get; set; }
        public Nullable<bool> IsError { get; set; }
        public string TransactionDescription { get; set; }
    
        public virtual CreditImport Import { get; set; }
        public virtual Employee PREmployee { get; set; }
        public virtual CreditMerchant Merchant { get; set; }
    }
}
