// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Repository.VP.PM.BidBoreLineRepository.ProcessUpdate(portal.Models.Views.Bid.Wizard.BidBoreLineViewModel,System.Web.Mvc.ModelStateDictionary)~portal.Models.VP.PM.BidBoreLineViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Repository.VP.PM.BidBoreLineRepository.ProcessUpdate(portal.Models.Views.Bid.BidBoreLineViewModel,System.Web.Mvc.ModelStateDictionary)~portal.Models.VP.PM.BidBoreLineViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Models.Views.Bid.BoreLine.CostItemListViewModel.#ctor(portal.Code.Data.VP.BidBoreLine)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Repository.VP.PM.BidBoreLineRepository.ProcessUpdate(portal.Models.Views.Bid.BoreLineViewModel,System.Web.Mvc.ModelStateDictionary)~portal.Models.VP.PM.BidBoreLineViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Startup.ConfigureAuth(Owin.IAppBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:portal.MvcApplication.Application_Start")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:portal.MvcApplication.Application_Start")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:portal.ApplicationSignInManager.Create(Microsoft.AspNet.Identity.Owin.IdentityFactoryOptions{portal.ApplicationSignInManager},Microsoft.Owin.IOwinContext)~portal.ApplicationSignInManager")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:portal.ApplicationUserManager.Create(Microsoft.AspNet.Identity.Owin.IdentityFactoryOptions{portal.ApplicationUserManager},Microsoft.Owin.IOwinContext)~portal.ApplicationUserManager")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:portal.ApplicationUserManager.Create(Microsoft.AspNet.Identity.Owin.IdentityFactoryOptions{portal.ApplicationUserManager},Microsoft.Owin.IOwinContext)~portal.ApplicationUserManager")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:portal.Models.SendCodeViewModel.Providers")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:portal.Models.Views.Bid.BidPackageProductionRatePipeSizeListViewModel.List")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1810:Initialize reference type static fields inline", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Report.Controllers.ReportsController.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA3147:Mark Verb Handlers With Validate Antiforgery Token", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Controllers.ErrorController.LogJSError(System.String,System.String,System.Int32,System.String)~System.Web.Mvc.JsonResult")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:portal.ModelErrors.Errors")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Models.Views.Web.UserAccessLogListViewModel.#ctor(portal.Code.Data.VP.WebUserAccess)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:portal.ControllerAuthorizeAttribute.HandleUnauthorizedRequest(System.Web.Mvc.AuthorizationContext)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:portal.ValidateAntiForgeryTokenOnAllPostsAttribute.HTTP_HEADER_NAME")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:portal.ValidateAntiForgeryTokenOnAllPostsAttribute.OnAuthorization(System.Web.Mvc.AuthorizationContext)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:portal.HtmlExtensions.EnumDropDownListFor``2(System.Web.Mvc.HtmlHelper{``0},System.Linq.Expressions.Expression{System.Func{``0,``1}},System.Func{``1,System.Boolean},System.String,System.Object)~System.Web.Mvc.MvcHtmlString")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~P:portal.Models.Views.DailyTicket.DailyTicketSummaryViewModel.WorkDateString")]
[assembly: SuppressMessage("Security", "CA5363:Do Not Disable Request Validation", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Controllers.VP.WP.ForumController.Add(portal.Models.Views.Forums.ForumLineViewModel)~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Security", "CA3147:Mark Verb Handlers With Validate Antiforgery Token", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Controllers.VP.HQ.AttachmentController.Add(System.Byte,System.String,System.Int64,System.Nullable{System.Guid},System.String,System.String)~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Security", "CA3147:Mark Verb Handlers With Validate Antiforgery Token", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Controllers.VP.HQ.AttachmentController.AddFolder(System.Byte,System.Nullable{System.Guid},System.Int32,System.String)~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Security", "CA3147:Mark Verb Handlers With Validate Antiforgery Token", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Controllers.VP.HQ.AttachmentController.Delete(System.Byte,System.Int32)~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Security", "CA3147:Mark Verb Handlers With Validate Antiforgery Token", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Controllers.VP.HQ.AttachmentController.DeleteFolder(System.Byte,System.Nullable{System.Guid},System.Int32)~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Security", "CA3147:Mark Verb Handlers With Validate Antiforgery Token", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Controllers.VP.HQ.AttachmentController.DownloadFolder(System.Collections.Generic.List{portal.Models.Views.Attachment.AttachmentViewModel})~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Security", "CA3147:Mark Verb Handlers With Validate Antiforgery Token", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Controllers.VP.HQ.AttachmentController.UpdateFile(System.Byte,System.Int32,System.Int32,System.Int32,System.String)~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Security", "CA3147:Mark Verb Handlers With Validate Antiforgery Token", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Controllers.VP.HQ.AttachmentController.UpdateFolder(System.Byte,System.Nullable{System.Guid},System.Int32,System.Int32,System.String)~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:portal.ControllerAuthorizeAttribute.AuthorizeCore(System.Web.HttpContextBase)~System.Boolean")]
[assembly: SuppressMessage("Security", "CA3147:Mark Verb Handlers With Validate Antiforgery Token", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Controllers.View.HR.PRPayRateController.UploadProfilePicture(System.Byte,System.Int32)~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Usage", "CA2241:Provide correct arguments to formatting methods", Justification = "<Pending>", Scope = "member", Target = "~M:portal.Controllers.VP.HR.HRComboController.HRTestCodesTypeCombo(System.Byte,System.String)~System.Web.Mvc.JsonResult")]
