//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class APBatchHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APBatchHeader()
        {
            this.Lines = new HashSet<APBatchLine>();
        }
    
        [Key]
		public byte APCo { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public int BatchId { get; set; }
        [Key]
		public int BatchSeq { get; set; }
        public string BatchTransType { get; set; }
        public Nullable<int> APTransId { get; set; }
        public byte VendorGroupId { get; set; }
        public int VendorId { get; set; }
        public string APRef { get; set; }
        public string Description { get; set; }
        public System.DateTime InvDate { get; set; }
        public Nullable<System.DateTime> DiscDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public decimal InvTotal { get; set; }
        public string HoldCode { get; set; }
        public string PayControl { get; set; }
        public string PayMethod { get; set; }
        public byte CMCo { get; set; }
        public Nullable<short> CMAcct { get; set; }
        public string PrePaidYN { get; set; }
        public Nullable<System.DateTime> PrePaidMth { get; set; }
        public Nullable<System.DateTime> PrePaidDate { get; set; }
        public string PrePaidChk { get; set; }
        public Nullable<byte> PrePaidSeq { get; set; }
        public string PrePaidProcYN { get; set; }
        public string V1099YN { get; set; }
        public string V1099Type { get; set; }
        public Nullable<byte> V1099Box { get; set; }
        public string PayOverrideYN { get; set; }
        public string PayName { get; set; }
        public string PayAddress { get; set; }
        public string PayCity { get; set; }
        public string PayState { get; set; }
        public string PayZip { get; set; }
        public string InvId { get; set; }
        public Nullable<System.DateTime> UIMth { get; set; }
        public Nullable<short> UISeq { get; set; }
        public Nullable<byte> OldVendorGroup { get; set; }
        public Nullable<int> OldVendor { get; set; }
        public string OldAPRef { get; set; }
        public string OldDesc { get; set; }
        public Nullable<System.DateTime> OldInvDate { get; set; }
        public Nullable<System.DateTime> OldDiscDate { get; set; }
        public Nullable<System.DateTime> OldDueDate { get; set; }
        public Nullable<decimal> OldInvTotal { get; set; }
        public string OldHoldCode { get; set; }
        public string OldPayControl { get; set; }
        public string OldPayMethod { get; set; }
        public Nullable<byte> OldCMCo { get; set; }
        public Nullable<short> OldCMAcct { get; set; }
        public string OldPrePaidYN { get; set; }
        public Nullable<System.DateTime> OldPrePaidMth { get; set; }
        public Nullable<System.DateTime> OldPrePaidDate { get; set; }
        public string OldPrePaidChk { get; set; }
        public Nullable<byte> OldPrePaidSeq { get; set; }
        public string OldPrePaidProcYN { get; set; }
        public string Old1099YN { get; set; }
        public string Old1099Type { get; set; }
        public Nullable<byte> Old1099Box { get; set; }
        public string OldPayOverrideYN { get; set; }
        public string OldPayName { get; set; }
        public string OldPayAddress { get; set; }
        public string OldPayCity { get; set; }
        public string OldPayState { get; set; }
        public string OldPayZip { get; set; }
        public string PayAddInfo { get; set; }
        public string OldPayAddInfo { get; set; }
        public string DocName { get; set; }
        public string OldDocName { get; set; }
        public Nullable<byte> MSCo { get; set; }
        public string MSInv { get; set; }
        public Nullable<byte> AddendaTypeId { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<short> DLcode { get; set; }
        public string TaxFormCode { get; set; }
        public Nullable<System.DateTime> TaxPeriodEndDate { get; set; }
        public string AmountType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AmtType2 { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public string AmtType3 { get; set; }
        public Nullable<decimal> Amount3 { get; set; }
        public Nullable<byte> OldAddendaTypeId { get; set; }
        public Nullable<byte> OldPRCo { get; set; }
        public Nullable<int> OldEmployee { get; set; }
        public Nullable<short> OldDLcode { get; set; }
        public string OldTaxFormCode { get; set; }
        public Nullable<System.DateTime> OldTaxPeriodEndDate { get; set; }
        public string OldAmountType { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public string OldAmtType2 { get; set; }
        public Nullable<decimal> OldAmount2 { get; set; }
        public string OldAmtType3 { get; set; }
        public Nullable<decimal> OldAmount3 { get; set; }
        public string SeparatePayYN { get; set; }
        public string OldSeparatePayYN { get; set; }
        public string ChkRev { get; set; }
        public string PaidYN { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<byte> AddressSeq { get; set; }
        public Nullable<byte> OldAddressSeq { get; set; }
        public long KeyID { get; set; }
        public Nullable<long> SLKeyID { get; set; }
        public string PayCountry { get; set; }
        public string OldPayCountry { get; set; }
        public Nullable<long> CCTransId { get; set; }
        public string MerchantId { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual HQCompanyParm Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APBatchLine> Lines { get; set; }
        public virtual APVendor Vendor { get; set; }
        public virtual HQAttachment HQAttachment { get; set; }
        public virtual APCompanyParm bAPCO { get; set; }
    }
}
