//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class APPaymentBatchSequance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPaymentBatchSequance()
        {
            this.Transactions = new HashSet<APPaymentBatchSequanceTransaction>();
        }
    
        [Key]
		public byte APCo { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public int BatchId { get; set; }
        [Key]
		public int BatchSeqId { get; set; }
        public byte CMCo { get; set; }
        public short CMAcct { get; set; }
        public string PayMethod { get; set; }
        public string CMRef { get; set; }
        public Nullable<byte> CMRefSeq { get; set; }
        public Nullable<short> EFTSeq { get; set; }
        public string ChkType { get; set; }
        public byte VendorGroup { get; set; }
        public int VendorId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> Supplier { get; set; }
        public string VoidYN { get; set; }
        public string VoidMemo { get; set; }
        public string ReuseYN { get; set; }
        public string Overflow { get; set; }
        public string AddnlInfo { get; set; }
        public Nullable<byte> AddendaTypeId { get; set; }
        public string TaxFormCode { get; set; }
        public Nullable<int> Employee { get; set; }
        public string SeparatePayYN { get; set; }
        public Nullable<System.DateTime> SeparatePayMth { get; set; }
        public Nullable<int> SeparatePayTrans { get; set; }
        public string JobId { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string SL { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string PayOverrideYN { get; set; }
        public Nullable<byte> AddressSeq { get; set; }
        public long KeyID { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public Nullable<long> CCTransId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPaymentBatchSequanceTransaction> Transactions { get; set; }
    }
}
