//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class APTransLinePayment
    {
        [Key]
		public byte APCo { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public int APTransId { get; set; }
        [Key]
		public short APLineId { get; set; }
        [Key]
		public byte APSeqId { get; set; }
        public byte PayType { get; set; }
        public decimal Amount { get; set; }
        public decimal DiscOffer { get; set; }
        public decimal DiscTaken { get; set; }
        public System.DateTime DueDate { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> PaidMth { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<byte> CMCo { get; set; }
        public Nullable<short> CMAcct { get; set; }
        public string PayMethod { get; set; }
        public string CMRef { get; set; }
        public Nullable<byte> CMRefSeq { get; set; }
        public Nullable<short> EFTSeq { get; set; }
        public Nullable<byte> VendorGroup { get; set; }
        public Nullable<int> Supplier { get; set; }
        public Nullable<int> PayCategory { get; set; }
        public long KeyID { get; set; }
        public Nullable<decimal> GSTtaxAmt { get; set; }
        public Nullable<decimal> TotTaxAmount { get; set; }
        public string AuditYN { get; set; }
        public Nullable<decimal> OldGSTtaxAmt { get; set; }
        public string ExpenseGST { get; set; }
        public Nullable<decimal> PSTtaxAmt { get; set; }
        public Nullable<decimal> OldPSTtaxAmt { get; set; }
    
        public virtual APPaymentLine PaymentLine { get; set; }
        public virtual APTransLine APTransLine { get; set; }
    }
}
