//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class APTransLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APTransLine()
        {
            this.Payments = new HashSet<APTransLinePayment>();
            this.JobCosts = new HashSet<JobCost>();
        }
    
        [Key]
		public byte APCo { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public int APTransId { get; set; }
        [Key]
		public short APLineId { get; set; }
        public byte LineType { get; set; }
        public string PO { get; set; }
        public Nullable<short> POItem { get; set; }
        public Nullable<byte> ItemTypeId { get; set; }
        public string SL { get; set; }
        public Nullable<short> SLItem { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string JobId { get; set; }
        public Nullable<byte> PhaseGroupId { get; set; }
        public string PhaseId { get; set; }
        public Nullable<byte> JCCType { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public string WO { get; set; }
        public Nullable<short> WOItem { get; set; }
        public string EquipmentId { get; set; }
        public Nullable<byte> EMGroupId { get; set; }
        public string CostCodeId { get; set; }
        public Nullable<byte> EMCType { get; set; }
        public string CompType { get; set; }
        public string Component { get; set; }
        public Nullable<byte> INCo { get; set; }
        public string Loc { get; set; }
        public Nullable<byte> MatlGroup { get; set; }
        public string Material { get; set; }
        public byte GLCo { get; set; }
        public string GLAcct { get; set; }
        public string Description { get; set; }
        public string UM { get; set; }
        public decimal Units { get; set; }
        public decimal UnitCost { get; set; }
        public string ECM { get; set; }
        public Nullable<byte> VendorGroupId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public byte PayType { get; set; }
        public decimal GrossAmt { get; set; }
        public decimal MiscAmt { get; set; }
        public string MiscYN { get; set; }
        public Nullable<byte> TaxGroup { get; set; }
        public string TaxCodeId { get; set; }
        public Nullable<byte> TaxTypeId { get; set; }
        public decimal TaxBasis { get; set; }
        public decimal TaxAmt { get; set; }
        public decimal Retainage { get; set; }
        public decimal Discount { get; set; }
        public decimal BurUnitCost { get; set; }
        public string BECM { get; set; }
        public string Notes { get; set; }
        public string POPayTypeYN { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<int> PayCategory { get; set; }
        public long KeyID { get; set; }
        public string Receiver_ { get; set; }
        public Nullable<long> SLKeyID { get; set; }
        public Nullable<byte> SMCo { get; set; }
        public Nullable<int> SMWorkOrder { get; set; }
        public Nullable<int> Scope { get; set; }
        public string SMStandardItem { get; set; }
        public Nullable<int> POItemLine { get; set; }
        public Nullable<short> SMCostType { get; set; }
        public Nullable<byte> SMJCCostType { get; set; }
        public Nullable<byte> SMPhaseGroup { get; set; }
        public string SubjToOnCostYN { get; set; }
        public Nullable<byte> OnCostStatus { get; set; }
        public Nullable<System.DateTime> ocApplyMth { get; set; }
        public Nullable<int> ocApplyTrans { get; set; }
        public Nullable<short> ocApplyLine { get; set; }
        public string ATOCategory { get; set; }
        public string ocSchemeID { get; set; }
        public string ocMembershipNbr { get; set; }
        public string SMPhase { get; set; }
        public decimal SMTaxLiability { get; set; }
        public Nullable<int> EmpNumber { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Vendor { get; set; }
        public string CCReference { get; set; }
        public string MerchGroup { get; set; }
        public Nullable<long> CCTransId { get; set; }
        public Nullable<int> CCCodingSeqId { get; set; }
    
        public virtual APVendor Supplier { get; set; }
        public virtual GLAccount GLAccount { get; set; }
        public virtual TaxCode bHQTX { get; set; }
        public virtual APTran APTran { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APTransLinePayment> Payments { get; set; }
        public virtual EMCostCode EMCostCode { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual JobPhase JobPhase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCost> JobCosts { get; set; }
    }
}
