//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class APVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APVendor()
        {
            this.ProjectFirms = new HashSet<Firm>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PORequests = new HashSet<PORequest>();
            this.Phases = new HashSet<VendorPhase>();
            this.Documents = new HashSet<APDocument>();
            this.DocumentSeqs = new HashSet<APDocumentSeq>();
            this.SupplierAPLines = new HashSet<APTransLine>();
            this.APTransactions = new HashSet<APTran>();
            this.Merchants = new HashSet<CreditMerchant>();
            this.AltAddresses = new HashSet<VendorAltAddress>();
            this.bAPHBs = new HashSet<APBatchHeader>();
            this.bPOHBs = new HashSet<POBatchHeader>();
            this.bAPPHs = new HashSet<APPayment>();
        }
    
        [Key]
		public byte VendorGroupId { get; set; }
        [Key]
		public int VendorId { get; set; }
        public string SortName { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string TempYN { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string URL { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Address2 { get; set; }
        public string POAddress { get; set; }
        public string POCity { get; set; }
        public string POState { get; set; }
        public string POZip { get; set; }
        public string POAddress2 { get; set; }
        public string Purge { get; set; }
        public Nullable<byte> CustGroup { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<byte> TaxGroup { get; set; }
        public string TaxCode { get; set; }
        public string PayTerms { get; set; }
        public byte GLCo { get; set; }
        public string GLAcct { get; set; }
        public string V1099YN { get; set; }
        public string V1099Type { get; set; }
        public Nullable<byte> V1099Box { get; set; }
        public string TaxId { get; set; }
        public string Prop { get; set; }
        public string ActiveYN { get; set; }
        public string EFT { get; set; }
        public string RoutingId { get; set; }
        public string BankAcct { get; set; }
        public string AcctType { get; set; }
        public Nullable<System.DateTime> LastInvDate { get; set; }
        public string AuditYN { get; set; }
        public string Notes { get; set; }
        public string AddnlInfo { get; set; }
        public Nullable<byte> AddendaTypeId { get; set; }
        public string Reviewer { get; set; }
        public string SeparatePayInvYN { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string OverrideMinAmtYN { get; set; }
        public Nullable<int> MasterVendor { get; set; }
        public byte APRefUnqOvr { get; set; }
        public string ICFirstName { get; set; }
        public string ICMInitial { get; set; }
        public string ICLastName { get; set; }
        public string ICSocSecNbr { get; set; }
        public string ICStreetNbr { get; set; }
        public string ICStreetName { get; set; }
        public string ICAptNbr { get; set; }
        public string ICCity { get; set; }
        public string ICState { get; set; }
        public string ICZip { get; set; }
        public Nullable<System.DateTime> ICLastRptDate { get; set; }
        public string UpdatePMYN { get; set; }
        public long KeyID { get; set; }
        public string AddRevToAllLinesYN { get; set; }
        public string Country { get; set; }
        public string POCountry { get; set; }
        public string ICCountry { get; set; }
        public string AUVendorEFTYN { get; set; }
        public string AUVendorAccountNumber { get; set; }
        public string AUVendorBSB { get; set; }
        public string AUVendorReference { get; set; }
        public string IATYN { get; set; }
        public string ISODestinationCountryCode { get; set; }
        public string RDFIBankName { get; set; }
        public string BranchCountryCode { get; set; }
        public string RDFIIdentNbrQualifier { get; set; }
        public string GatewayOperatorRDFIIdent { get; set; }
        public Nullable<short> CMAcct { get; set; }
        public string PayInfoDelivMthd { get; set; }
        public string T5FirstName { get; set; }
        public string T5MiddleInit { get; set; }
        public string T5LastName { get; set; }
        public string T5SocInsNbr { get; set; }
        public string T5BusinessNbr { get; set; }
        public string T5BusTypeCode { get; set; }
        public string T5PartnerFIN { get; set; }
        public string AusBusNbr { get; set; }
        public string AusCorpNbr { get; set; }
        public string PayControl { get; set; }
        public string CASubjToWC { get; set; }
        public string CAClearanceCert { get; set; }
        public Nullable<System.DateTime> CACertEffectiveDate { get; set; }
        public Nullable<byte> V1099AddressSeq { get; set; }
        public string PayMethod { get; set; }
        public string SubjToOnCostYN { get; set; }
        public string CSEmail { get; set; }
        public Nullable<byte> OnCostCostType { get; set; }
        public string udVendorType { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> IsReoccurring { get; set; }
        public Nullable<bool> IsReceiptRequired { get; set; }
        public string DefaultGLAcct { get; set; }
        public string DefaultJCPhaseId { get; set; }
        public Nullable<byte> DefaultJCCType { get; set; }
        public string DefaultEMCostCodeId { get; set; }
        public Nullable<byte> DefaultEMCType { get; set; }
        public string MerchantMatchString { get; set; }
        public Nullable<byte> DefaultLineTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Firm> ProjectFirms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORequest> PORequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorPhase> Phases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APDocument> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APDocumentSeq> DocumentSeqs { get; set; }
        public virtual PayTerm PayTerm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APTransLine> SupplierAPLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APTran> APTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditMerchant> Merchants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorAltAddress> AltAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APBatchHeader> bAPHBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POBatchHeader> bPOHBs { get; set; }
        public virtual HQGroup HQGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPayment> bAPPHs { get; set; }
    }
}
