//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class BatchError
    {
        [Key]
		public byte Co { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public int BatchId { get; set; }
        [Key]
		public int Seq { get; set; }
        public string ErrorText { get; set; }
        public byte Severity { get; set; }
    
        public virtual Batch Batch { get; set; }
    }
}
