//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class BidCustomer
    {
        [Key]
		public byte BDCo { get; set; }
        [Key]
		public int BidId { get; set; }
        [Key]
		public int LineId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> BidStatus { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<bool> IsAwarded { get; set; }
        public Nullable<byte> CustGroupId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Bid Bid { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
