//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class BidPackageProductionRate
    {
        [Key]
		public byte BDCo { get; set; }
        [Key]
		public int BidId { get; set; }
        [Key]
		public int PackageId { get; set; }
        [Key]
		public int LineId { get; set; }
        public Nullable<decimal> PipeSize { get; set; }
        public string PhaseId { get; set; }
        public Nullable<int> GroundDensityId { get; set; }
        public Nullable<int> PassId { get; set; }
        public Nullable<decimal> BoreSize { get; set; }
        public Nullable<decimal> ProductionRate { get; set; }
        public string UM { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public Nullable<decimal> ProductionDays { get; set; }
        public Nullable<int> ProductionCalTypeId { get; set; }
        public Nullable<int> ShiftCnt { get; set; }
        public Nullable<decimal> Shift2ProductionPerc { get; set; }
    
        public virtual PhaseMaster Phase { get; set; }
        public virtual GroundDensity GroundDensity { get; set; }
        public virtual BidPackage Package { get; set; }
    }
}
