//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class BidPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BidPackage()
        {
            this.BoreLines = new HashSet<BidBoreLine>();
            this.ProductionRates = new HashSet<BidPackageProductionRate>();
            this.CostItems = new HashSet<BidCostItem>();
            this.Scopes = new HashSet<BidPackageScope>();
            this.SubPackages = new HashSet<BidPackage>();
            this.PackageCosts = new HashSet<BidPackageCost>();
            this.Crews = new HashSet<BDPackageCrew>();
            this.vBoreLineCostItems = new HashSet<vBidBoreLineCostItem>();
            this.GroundDensities = new HashSet<BidPackageDensity>();
            this.vBidBoreLines = new HashSet<vBidBoreLine>();
        }
    
        [Key]
		public byte BDCo { get; set; }
        [Key]
		public int BidId { get; set; }
        [Key]
		public int PackageId { get; set; }
        public string Description { get; set; }
        public Nullable<int> tNumberOfBores { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> DirtGM { get; set; }
        public Nullable<decimal> RockGM { get; set; }
        public Nullable<System.DateTime> tStartDate { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public Nullable<int> tBoreTypeId { get; set; }
        public Nullable<decimal> tPipeSize { get; set; }
        public string tRigCategoryId { get; set; }
        public Nullable<int> tGroundDensityId { get; set; }
        public Nullable<decimal> DirtPrice { get; set; }
        public Nullable<decimal> RockPrice { get; set; }
        public Nullable<int> tStatusId { get; set; }
        public Nullable<int> tCustomerId { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string tJobId { get; set; }
        public Nullable<int> tDivisionId { get; set; }
        public string tCustomerReference { get; set; }
        public Nullable<bool> IncludeOnProposal { get; set; }
        public Nullable<int> ParentPackageId { get; set; }
        public Nullable<decimal> TotalDayRounding { get; set; }
        public string RoundingPhaseId { get; set; }
        public Nullable<int> tIndustryId { get; set; }
        public Nullable<int> tMarketId { get; set; }
        public string CrewId { get; set; }
        public string RigId { get; set; }
        public Nullable<int> GanttId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<byte> CustGroupId { get; set; }
    
        public virtual Bid Bid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLine> BoreLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackageProductionRate> ProductionRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidCostItem> CostItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackageScope> Scopes { get; set; }
        public virtual EquipmentCategory RigCategory { get; set; }
        public virtual GroundDensity GroundDensity { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackage> SubPackages { get; set; }
        public virtual BidPackage ParentPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackageCost> PackageCosts { get; set; }
        public virtual JCIndustry Industry { get; set; }
        public virtual JCMarket Market { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BDPackageCrew> Crews { get; set; }
        public virtual PMProjectGanttTask ProjectGanttTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vBidBoreLineCostItem> vBoreLineCostItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackageDensity> GroundDensities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vBidBoreLine> vBidBoreLines { get; set; }
        public virtual ProjectDivision Division { get; set; }
        public virtual Job Project { get; set; }
        public virtual BidBoreType budBDBT { get; set; }
    }
}
