//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class CreditTransactionCode
    {
        [Key]
		public byte CCCo { get; set; }
        [Key]
		public long TransId { get; set; }
        [Key]
		public int SeqId { get; set; }
        public string Material { get; set; }
        public string Description { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string tJobId { get; set; }
        public Nullable<byte> PhaseGroupId { get; set; }
        public string tPhaseId { get; set; }
        public Nullable<byte> tJCCType { get; set; }
        public string CrewId { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public string tEquipmentId { get; set; }
        public Nullable<byte> EMGroupId { get; set; }
        public string tCostCodeId { get; set; }
        public Nullable<byte> tEMCType { get; set; }
        public string tGLAcct { get; set; }
        public Nullable<decimal> Units { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string UM { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Comments { get; set; }
        public Nullable<byte> TaxTypeId { get; set; }
        public string TaxCodeId { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<byte> tLineTypeId { get; set; }
        public string tPO { get; set; }
        public Nullable<short> tPOItemId { get; set; }
        public Nullable<int> POItemLine { get; set; }
        public Nullable<byte> tPOItemTypeId { get; set; }
        public string WO { get; set; }
        public Nullable<short> WOItem { get; set; }
        public Nullable<byte> GLCo { get; set; }
        public Nullable<decimal> GrossAmt { get; set; }
        public Nullable<decimal> MiscAmt { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<byte> POCo { get; set; }
        public string UniqueTransId { get; set; }
    
        public virtual EMCostCode EquipmentCostCode { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual CostType JobCostType { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobPhase JobPhase { get; set; }
        public virtual CreditTransaction Transaction { get; set; }
        public virtual CompanyDivision Division { get; set; }
        public virtual JobPhaseCost JobPhaseCost { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual PurchaseOrderItem POItem { get; set; }
    }
}
