//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class CreditImageLink
    {
        [Key]
		public byte CCCo { get; set; }
        [Key]
		public int EmployeeId { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public int ImageId { get; set; }
        [Key]
		public int LinkId { get; set; }
        public Nullable<long> TransId { get; set; }
        public Nullable<System.DateTime> TaggedDate { get; set; }
        public string UniqueTransId { get; set; }
    
        public virtual CreditTransaction Transaction { get; set; }
        public virtual CreditCardImage Image { get; set; }
    }
}
