//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class CreditTransactionAttachment
    {
        [Key]
		public byte Co { get; set; }
        [Key]
		public long TransId { get; set; }
        [Key]
		public int ImageId { get; set; }
        public string ReceiptImageRefId { get; set; }
        public string ImageName { get; set; }
    
        public virtual CreditTransaction Transaction { get; set; }
    }
}
