//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class DailyTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyTicket()
        {
            this.DailyEmployeeEntries = new HashSet<DailyEmployeeEntry>();
            this.DailyEmployeePerdiems = new HashSet<DailyEmployeePerdiem>();
            this.DailyEquipments = new HashSet<DailyEquipment>();
            this.DailyJobEmployees = new HashSet<DailyJobEmployee>();
            this.DailyTicketStatusLogs = new HashSet<DailyStatusLog>();
            this.XXX_DailyJobTasks = new HashSet<DNU_DailyJobTask>();
            this.budDTPEs = new HashSet<DEL_DailyPayrollEntry>();
            this.DTPayrollHours = new HashSet<DTPayrollHour>();
            this.DTPayrollPerdiems = new HashSet<DTPayrollPerdiem>();
            this.EquipmentUsages = new HashSet<DailyEquipmentUsage>();
            this.POUsages = new HashSet<DailyPOUsage>();
        }
    
        [Key]
		public byte DTCo { get; set; }
        [Key]
		public int TicketId { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<System.DateTime> tWorkDate { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> tStatusId { get; set; }
        public Nullable<int> ParentTicketId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ProcessedBy { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public Nullable<int> OldTicketId { get; set; }
        public Nullable<int> GanttId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> WorkFlowId { get; set; }
    
        public virtual WebUser ApprovedUser { get; set; }
        public virtual WebUser CreatedUser { get; set; }
        public virtual WebUser ModifiedUser { get; set; }
        public virtual WebUser ProcessedUser { get; set; }
        public virtual WebUser SubmittedUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEmployeeEntry> DailyEmployeeEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEmployeePerdiem> DailyEmployeePerdiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEquipment> DailyEquipments { get; set; }
        public virtual DailyEmployeeTicket DailyEmployeeTicket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyJobEmployee> DailyJobEmployees { get; set; }
        public virtual DailyJobTicket DailyJobTicket { get; set; }
        public virtual DailyPMTicket DailyProjectMangerTicket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyStatusLog> DailyTicketStatusLogs { get; set; }
        public virtual DailyShopTicket DailyShopTicket { get; set; }
        public virtual DailyTruckTicket DailyTruckTicket { get; set; }
        public virtual DailySubContractorTicket DailySubContractorTicket { get; set; }
        public virtual Calendar Calendar { get; set; }
        public virtual DailyForm Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNU_DailyJobTask> XXX_DailyJobTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEL_DailyPayrollEntry> budDTPEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTPayrollHour> DTPayrollHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTPayrollPerdiem> DTPayrollPerdiems { get; set; }
        public virtual HQCompanyParm HQCompanyParm { get; set; }
        public virtual DailyGeneralTicket GeneralTicket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEquipmentUsage> EquipmentUsages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyPOUsage> POUsages { get; set; }
        public virtual PMProjectGanttTask ProjectGanttTask { get; set; }
        public virtual WorkFlow WorkFlow { get; set; }
    }
}
