//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class DailyEmployeeTicket
    {
        [Key]
		public byte DTCo { get; set; }
        [Key]
		public int TicketId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public Nullable<int> WeekId { get; set; }
        public string Comments { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
    
        public virtual DailyTicket DailyTicket { get; set; }
        public virtual WebUser ModifiedUser { get; set; }
        public virtual Employee PREmployee { get; set; }
    }
}
