//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class DailyEquipmentUsage
    {
        [Key]
		public byte DTCo { get; set; }
        [Key]
		public int TicketId { get; set; }
        [Key]
		public int SeqId { get; set; }
        public string BatchTransType { get; set; }
        public Nullable<byte> EMGroupId { get; set; }
        public string EquipmentId { get; set; }
        public string RevCodeId { get; set; }
        public string EMTransType { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public string Description { get; set; }
        public Nullable<byte> GLCo { get; set; }
        public string GLTransAcct { get; set; }
        public string GLOffsetAcct { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public Nullable<int> PREmployee { get; set; }
        public string UM { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string JobId { get; set; }
        public Nullable<byte> PhaseGroupId { get; set; }
        public string JCPhaseId { get; set; }
        public Nullable<byte> JCCostType { get; set; }
        public Nullable<decimal> RevRate { get; set; }
        public Nullable<decimal> RevWorkUnits { get; set; }
        public Nullable<decimal> RevTimeUnits { get; set; }
        public Nullable<decimal> RevDollars { get; set; }
        public Nullable<decimal> PreviousHourMeter { get; set; }
        public Nullable<decimal> CurrentHourMeter { get; set; }
        public Nullable<decimal> PreviousOdometer { get; set; }
        public Nullable<decimal> CurrentOdometer { get; set; }
        public string TimeUM { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<byte> EMCo { get; set; }
    
        public virtual DailyTicket DailyTicket { get; set; }
        public virtual HQCompanyParm Company { get; set; }
        public virtual Calendar Calendar { get; set; }
        public virtual EMRevCodes RevCode { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Job Job { get; set; }
    }
}
