//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class DailyPOUsage
    {
        [Key]
		public byte DTCo { get; set; }
        [Key]
		public int TicketId { get; set; }
        [Key]
		public int LineId { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public string JobId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string PO { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string BudgetCodeId { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public Nullable<byte> VendGroup { get; set; }
        public Nullable<byte> POCo { get; set; }
    
        public virtual DailyTicket Ticket { get; set; }
    }
}
