//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class DDFIShared
    {
        public string Form { get; set; }
        public Nullable<short> Seq { get; set; }
        public string ViewName { get; set; }
        public string ColumnName { get; set; }
        public string Description { get; set; }
        public string Datatype { get; set; }
        public Nullable<byte> InputType { get; set; }
        public string InputMask { get; set; }
        public Nullable<short> InputLength { get; set; }
        public Nullable<byte> Prec { get; set; }
        public string ActiveLookup { get; set; }
        public string LookupParams { get; set; }
        public Nullable<byte> LookupLoadSeq { get; set; }
        public string SetupForm { get; set; }
        public string SetupParams { get; set; }
        public string StatusText { get; set; }
        public Nullable<byte> Tab { get; set; }
        public string Req { get; set; }
        public string ValProc { get; set; }
        public string ValParams { get; set; }
        public Nullable<byte> ValLevel { get; set; }
        public string SecondaryValProc { get; set; }
        public string SecondaryValParams { get; set; }
        public Nullable<byte> SecondaryValLevel { get; set; }
        public Nullable<byte> UpdateGroup { get; set; }
        public Nullable<byte> ControlType { get; set; }
        public string ControlPosition { get; set; }
        public Nullable<byte> FieldType { get; set; }
        public string HelpKeyword { get; set; }
        public string DescriptionColumn { get; set; }
        public Nullable<short> GridCol { get; set; }
        [Key]
		public byte DefaultType { get; set; }
        public string DefaultValue { get; set; }
        [Key]
		public string InputSkip { get; set; }
        public string Label { get; set; }
        public string ShowForm { get; set; }
        public string ShowGrid { get; set; }
        public Nullable<byte> AutoSeqType { get; set; }
        public string MinValue { get; set; }
        public string MaxValue { get; set; }
        public string ValExpression { get; set; }
        public string ValExpError { get; set; }
        public string ComboType { get; set; }
        public string GridColHeading { get; set; }
        public Nullable<short> HeaderLinkSeq { get; set; }
        public string CustomControlSize { get; set; }
        public string Computed { get; set; }
        public Nullable<byte> ShowDesc { get; set; }
        public Nullable<short> ColWidth { get; set; }
        public Nullable<short> DescriptionColWidth { get; set; }
        public string IsFormFilter { get; set; }
        [Key]
		public string Custom { get; set; }
        public string Status { get; set; }
        public Nullable<int> LabelTextID { get; set; }
        public Nullable<int> ColumnTextID { get; set; }
        public string ShowInQueryFilter { get; set; }
        public string ShowInQueryResultSet { get; set; }
        public string QueryColumnName { get; set; }
        public string ExcludeFromRecordCopy { get; set; }
        public string CustomGridColHeading { get; set; }
        public string ExcludeFromAggregation { get; set; }
        public string MaskText { get; set; }
        public string DisableInput { get; set; }
        public Nullable<byte> ShowInSearchLabel { get; set; }
    }
}
