//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class DTPayrollPerdiem
    {
        [Key]
		public byte PRCo { get; set; }
        [Key]
		public int EmployeeId { get; set; }
        [Key]
		public System.DateTime WorkDate { get; set; }
        [Key]
		public int LineNum { get; set; }
        public int TicketId { get; set; }
        public int TicketLineNum { get; set; }
        public Nullable<int> EntryTypeId { get; set; }
        public string EquipmentId { get; set; }
        public string JobId { get; set; }
        public Nullable<byte> PhaseGroupId { get; set; }
        public string PhaseId { get; set; }
        public Nullable<byte> CostTypeId { get; set; }
        public Nullable<int> PerdiemId { get; set; }
        public Nullable<int> PerdiemIdAdj { get; set; }
        public Nullable<short> EarnCodeId { get; set; }
        public string Comments { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string PayrollBy { get; set; }
        public Nullable<System.DateTime> PayrollOn { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> BatchSeq { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public Nullable<byte> DTCo { get; set; }
        public string WorkOrderId { get; set; }
        public Nullable<short> WorkOrderItemId { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual CostType CostType { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobPhase JobPhase { get; set; }
        public virtual EarnCode EarnCode { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual DailyTicket DailyTicket { get; set; }
        public virtual Calendar Calendar { get; set; }
        public virtual WebUser ModifiedUser { get; set; }
        public virtual WebUser PayrollUser { get; set; }
        public virtual HQCompanyParm XXX_Company { get; set; }
    }
}
