//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class EMCompanyParm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMCompanyParm()
        {
            this.Equipments = new HashSet<Equipment>();
            this.bEMRHs = new HashSet<EMRevRate>();
            this.bEMMRs = new HashSet<EquipmentMeterLog>();
            this.Locations = new HashSet<EMLocation>();
            this.Categories = new HashSet<EquipmentCategory>();
            this.AuditApprovers = new HashSet<EMAuditApprover>();
            this.bEMDGs = new HashSet<EMDepartmentCostTypeGLAcct>();
            this.bEMDOes = new HashSet<EMDeptCostCodeGLAccount>();
            this.EMWorkOrders = new HashSet<EMWorkOrder>();
            this.bEMWIs = new HashSet<EMWorkOrderItem>();
            this.bEMWPs = new HashSet<EMWorkOrderPart>();
            this.WOStatusCodes = new HashSet<EMWorkOrderStatusCode>();
            this.EquipmentAudits = new HashSet<EMAudit>();
        }
    
        [Key]
		public byte EMCo { get; set; }
        public byte EMGroupId { get; set; }
        public Nullable<byte> INCo { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public byte GLCo { get; set; }
        public Nullable<byte> AdjstGLLvl { get; set; }
        public string AdjstGLSumDesc { get; set; }
        public string AdjstGLDetlDesc { get; set; }
        public string AdjstGLJrnl { get; set; }
        public string UseAutoGL { get; set; }
        public Nullable<byte> UseGLLvl { get; set; }
        public string UseGLSumDesc { get; set; }
        public string UseGLDetlDesc { get; set; }
        public string UseGLJrnl { get; set; }
        public string UseRateOride { get; set; }
        public string UseRevBkdwnCodeDefault { get; set; }
        public string HoursUM { get; set; }
        public Nullable<byte> MatlGLLvl { get; set; }
        public string MatlGLSumDesc { get; set; }
        public string MatlGLDetlDesc { get; set; }
        public string MatlGLJrnl { get; set; }
        public string MatlMiscGLAcct { get; set; }
        public string MatlTax { get; set; }
        public string MatlValid { get; set; }
        public string DeprCalcReqd { get; set; }
        public Nullable<System.DateTime> DeprLstMnthCalc { get; set; }
        public Nullable<System.DateTime> DeprLstMnthBdgted { get; set; }
        public string DeprCostCode { get; set; }
        public Nullable<byte> DeprCostType { get; set; }
        public string GLOverride { get; set; }
        public string WOBeginStat { get; set; }
        public string WOCostCodeChg { get; set; }
        public string WOPostFinal { get; set; }
        public string WOBeginPartStatus { get; set; }
        public string WODefaultRepType { get; set; }
        public Nullable<byte> LaborCT { get; set; }
        public string LaborCostCodeChg { get; set; }
        public Nullable<byte> PartsCT { get; set; }
        public Nullable<byte> OutsideRprCT { get; set; }
        public string FuelCostCode { get; set; }
        public Nullable<byte> FuelCostType { get; set; }
        public string CompPostCosts { get; set; }
        public string CompUnattachedEquip { get; set; }
        public string AuditCompany { get; set; }
        public string AuditEquipment { get; set; }
        public string AuditDepartmentGL { get; set; }
        public string AuditAsset { get; set; }
        public string AuditRevenueRateCateg { get; set; }
        public string AuditRevenueRateEquip { get; set; }
        public string AuditLocXfer { get; set; }
        public string AuditCompXfer { get; set; }
        public string Notes { get; set; }
        public string WOAutoSeq { get; set; }
        public string WorkOrderOption { get; set; }
        public string LastWorkOrder { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string UsageMeterUpdate { get; set; }
        public string CostPartsMeterUpdate { get; set; }
        public string FuelMeterUpdate { get; set; }
        public string JobLocationUpdate { get; set; }
        public string ShowAllWO { get; set; }
        public string AllSMG { get; set; }
        public long KeyID { get; set; }
        public string MatlLastUsedYN { get; set; }
        public string AttachBatchReportsYN { get; set; }
        public string DefaultWarrantyStartDate { get; set; }
        public string AuditWarrantys { get; set; }
        public string AlwaysInitLinkedSMG { get; set; }
        public Nullable<byte> udJCUsageCt { get; set; }
        public string AuditAutoProcess { get; set; }
        public string AuditAutoBatch { get; set; }
        public string AuditAppover { get; set; }
        public string LaborCostCodeId { get; set; }
    
        public virtual HQCompanyParm HQCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMRevRate> bEMRHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentMeterLog> bEMMRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMLocation> Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentCategory> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAuditApprover> AuditApprovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMDepartmentCostTypeGLAcct> bEMDGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMDeptCostCodeGLAccount> bEMDOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMWorkOrder> EMWorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMWorkOrderItem> bEMWIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMWorkOrderPart> bEMWPs { get; set; }
        public virtual EMCostCode LaborCostCode { get; set; }
        public virtual EMWorkOrderStatusCode WOBeginStatusCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMWorkOrderStatusCode> WOStatusCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAudit> EquipmentAudits { get; set; }
    }
}
