//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class EMCostCodeType
    {
        [Key]
		public byte EMGroupId { get; set; }
        [Key]
		public byte CostTypeId { get; set; }
        [Key]
		public string CostCodeId { get; set; }
        public string UM { get; set; }
    
        public virtual EMCostCode CostCode { get; set; }
        public virtual EMCostType CostType { get; set; }
        public virtual UnitofMeasure UnitofMeasure { get; set; }
        public virtual HQGroup bHQGP { get; set; }
    }
}
