//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.DirectReports = new HashSet<Employee>();
            this.Resource = new HashSet<HRResource>();
            this.CrewLeaders = new HashSet<Crew>();
            this.DailyEmployeeEntries = new HashSet<DailyEmployeeEntry>();
            this.DailyJobEmployees = new HashSet<DailyJobEmployee>();
            this.UserProfile = new HashSet<UserProfile>();
            this.PayrollEntries = new HashSet<DEL_DailyPayrollEntry>();
            this.PayrollHours = new HashSet<DTPayrollHour>();
            this.PayrollPerdiems = new HashSet<DTPayrollPerdiem>();
            this.bPRTHs = new HashSet<PayrollEntry>();
            this.bPRTBs = new HashSet<PRBatchTimeEntry>();
            this.budDTGTs = new HashSet<DailyGeneralTicket>();
            this.budPRLRs = new HashSet<LeaveRequest>();
            this.budPRRLs = new HashSet<LeaveRequestLine>();
            this.Leave = new HashSet<EmployeeLeave>();
            this.LeaveEntries = new HashSet<LeaveEntry>();
            this.bJCCDs = new HashSet<JobCost>();
            this.AssignedEquipment = new HashSet<Equipment>();
            this.budEMAAs = new HashSet<EMAuditApprover>();
            this.budDTEHs = new HashSet<EmployeeHouse>();
            this.CreditCardTransactions = new HashSet<CreditTransaction>();
            this.CreditCardImages = new HashSet<CreditCardImage>();
            this.bEMWIs = new HashSet<EMWorkOrderItem>();
            this.budSMRLs = new HashSet<SMRequestLine>();
            this.budEMELs = new HashSet<EquipmentLog>();
            this.budEMELs1 = new HashSet<EquipmentLog>();
            this.DTEmployeeTickets = new HashSet<DailyEmployeeTicket>();
            this.DTEmployeePerdiems = new HashSet<DailyEmployeePerdiem>();
            this.budPORHs = new HashSet<PORequest>();
            this.budWPDMs = new HashSet<CompanyDivision>();
            this.budCMZIs = new HashSet<ZionImport>();
            this.budCMID_WEX = new HashSet<CCWexImport>();
            this.budCMID_PRBENEFIT = new HashSet<PRImportBenefit>();
            this.budHRPRs = new HashSet<HRPositionRequest>();
            this.budHRPRs1 = new HashSet<HRPositionRequest>();
        }
    
        [Key]
		public byte PRCo { get; set; }
        [Key]
		public int EmployeeId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MidName { get; set; }
        public string SortName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Address2 { get; set; }
        public string Phone { get; set; }
        public string SSN { get; set; }
        public string RaceId { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public byte PRGroupId { get; set; }
        public string PRDept { get; set; }
        public string Craft { get; set; }
        public string Class { get; set; }
        public string InsCode { get; set; }
        public string TaxState { get; set; }
        public string UnempState { get; set; }
        public string InsState { get; set; }
        public string LocalCode { get; set; }
        public Nullable<byte> GLCo { get; set; }
        public string UseState { get; set; }
        public string UseIns { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string JobId { get; set; }
        public string CrewId { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public short EarnCodeId { get; set; }
        public decimal HrlyRate { get; set; }
        public decimal SalaryAmt { get; set; }
        public string OTOpt { get; set; }
        public Nullable<byte> OTSched { get; set; }
        public decimal JCFixedRate { get; set; }
        public decimal EMFixedRate { get; set; }
        public decimal YTDSUI { get; set; }
        public string OccupCat { get; set; }
        public string CatStatus { get; set; }
        public string DirDeposit { get; set; }
        public string RoutingId { get; set; }
        public string BankAcct { get; set; }
        public string AcctType { get; set; }
        public string ActiveYN { get; set; }
        public string PensionYN { get; set; }
        public string PostToAll { get; set; }
        public string CertYN { get; set; }
        public string ChkSort { get; set; }
        public string AuditYN { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string Email { get; set; }
        public string DefaultPaySeq { get; set; }
        public Nullable<byte> DDPaySeq { get; set; }
        public string Suffix { get; set; }
        public Nullable<byte> TradeSeq { get; set; }
        public Nullable<decimal> CSLimit { get; set; }
        public Nullable<byte> CSGarnGroup { get; set; }
        public string CSAllocMethod { get; set; }
        public Nullable<byte> Shift { get; set; }
        public string NonResAlienYN { get; set; }
        public long KeyID { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> HDAmt { get; set; }
        public Nullable<decimal> F1Amt { get; set; }
        public Nullable<decimal> LCFStock { get; set; }
        public Nullable<decimal> LCPStock { get; set; }
        public string NAICS { get; set; }
        public string AUEFTYN { get; set; }
        public string AUAccountNumber { get; set; }
        public string AUBSB { get; set; }
        public string AUReference { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public string EquipmentId { get; set; }
        public Nullable<byte> EMGroup { get; set; }
        public string PayMethodDelivery { get; set; }
        public string CPPQPPExempt { get; set; }
        public string EIExempt { get; set; }
        public string PPIPExempt { get; set; }
        public string TimesheetRevGroup { get; set; }
        public string UpdatePRAEYN { get; set; }
        public string WOTaxState { get; set; }
        public string WOLocalCode { get; set; }
        public string UseLocal { get; set; }
        public string UseUnempState { get; set; }
        public string UseInsState { get; set; }
        public Nullable<System.DateTime> NewHireActStartDate { get; set; }
        public Nullable<System.DateTime> NewHireActEndDate { get; set; }
        public string CellPhone { get; set; }
        public Nullable<System.DateTime> RecentRehireDate { get; set; }
        public Nullable<System.DateTime> RecentSeparationDate { get; set; }
        public string SeparationReason { get; set; }
        public string SeparationReasonExplanation { get; set; }
        public decimal SMFixedRate { get; set; }
        public string ArrearsActiveYN { get; set; }
        public decimal WeeklyHours { get; set; }
        public string ETPPostedYN { get; set; }
        public string FMCSAPHMSA { get; set; }
        public string CAProgramAccount { get; set; }
        public Nullable<int> ADPnumber { get; set; }
        public string PaycomNumber { get; set; }
        public Nullable<byte> PerDiemRate { get; set; }
        public string ZionsCC { get; set; }
        public string WEXID { get; set; }
        public Nullable<decimal> AdditionalSourceDedns { get; set; }
        public Nullable<decimal> AuthorizedSourceDedns { get; set; }
        public string ExemptHealthContribution { get; set; }
        public string AlwaysCalcQPIP { get; set; }
        public string PrintInFrench { get; set; }
        public string QCFileNumber { get; set; }
        public string PAYGIncomeType { get; set; }
        public string EmailW2YN { get; set; }
        public string Email1095CYN { get; set; }
        public string EmailT4YN { get; set; }
        public string EmailPAYGSumYN { get; set; }
        public Nullable<int> ReportsToId { get; set; }
        public string Nickname { get; set; }
        public Nullable<decimal> udDailyRate { get; set; }
        public Nullable<int> DivisionId { get; set; }
    
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> DirectReports { get; set; }
        public virtual Employee Supervisor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRResource> Resource { get; set; }
        public virtual Race Race { get; set; }
        public virtual EarnCode EarnCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crew> CrewLeaders { get; set; }
        public virtual Crew Crew { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEmployeeEntry> DailyEmployeeEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyJobEmployee> DailyJobEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEL_DailyPayrollEntry> PayrollEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTPayrollHour> PayrollHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTPayrollPerdiem> PayrollPerdiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollEntry> bPRTHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRBatchTimeEntry> bPRTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyGeneralTicket> budDTGTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRequest> budPRLRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRequestLine> budPRRLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeave> Leave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveEntry> LeaveEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCost> bJCCDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> AssignedEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAuditApprover> budEMAAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeHouse> budDTEHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditTransaction> CreditCardTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCardImage> CreditCardImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMWorkOrderItem> bEMWIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMRequestLine> budSMRLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentLog> budEMELs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentLog> budEMELs1 { get; set; }
        public virtual CompanyDivision Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEmployeeTicket> DTEmployeeTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEmployeePerdiem> DTEmployeePerdiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORequest> budPORHs { get; set; }
        public virtual PRCompanyParm PRCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyDivision> budWPDMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZionImport> budCMZIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCWexImport> budCMID_WEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRImportBenefit> budCMID_PRBENEFIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionRequest> budHRPRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionRequest> budHRPRs1 { get; set; }
    }
}
