//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class EMServiceEquipmentLink
    {
        [Key]
		public byte EMCo { get; set; }
        [Key]
		public int LinkId { get; set; }
        public string EquipmentId { get; set; }
        public Nullable<int> ServiceItemId { get; set; }
        public bool IsActive { get; set; }
        public bool IsOverride { get; set; }
        public Nullable<byte> OverrideDateIntervalTypeId { get; set; }
        public Nullable<int> OverrideDateInterval { get; set; }
        public Nullable<int> OverrideOdoInterval { get; set; }
        public Nullable<int> OverrideHourInterval { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public Nullable<System.DateTime> NextServiceDate { get; set; }
        public Nullable<int> NextOdo { get; set; }
        public Nullable<int> NextHour { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual EMServiceItem ServiceItem { get; set; }
    }
}
