//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class EMWorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMWorkOrder()
        {
            this.Items = new HashSet<EMWorkOrderItem>();
            this.Parts = new HashSet<EMWorkOrderPart>();
        }
    
        [Key]
		public byte EMCo { get; set; }
        [Key]
		public string WorkOrderId { get; set; }
        public string EquipmentId { get; set; }
        public string ShopId { get; set; }
        public string Description { get; set; }
        public string InvLoc { get; set; }
        public Nullable<int> MechanicID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<System.DateTime> DateSched { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> INCo { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public string AutoInitSessionID { get; set; }
        public byte ShopGroupId { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string Complete { get; set; }
        public long KeyID { get; set; }
    
        public virtual EMCompanyParm EMCompany { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMWorkOrderItem> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMWorkOrderPart> Parts { get; set; }
        public virtual HQGroup bHQGP { get; set; }
    }
}
