//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        [Key]
		public int ErrorId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Parameters { get; set; }
        public string ExceptionMessage { get; set; }
        public string ErrorMessage { get; set; }
        public string StackTrace { get; set; }
        public string Source { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string IP4Address { get; set; }
        public string IP6Address { get; set; }
        public string HostName { get; set; }
        public string UrlReferrer { get; set; }
    
        public virtual WebUser User { get; set; }
    }
}
