//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class GLAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GLAccount()
        {
            this.bAPTLs = new HashSet<APTransLine>();
            this.bEMDGs = new HashSet<EMDepartmentCostTypeGLAcct>();
            this.bEMDOes = new HashSet<EMDeptCostCodeGLAccount>();
        }
    
        [Key]
		public byte GLCo { get; set; }
        [Key]
		public string GLAcct { get; set; }
        public string Description { get; set; }
        public string AcctType { get; set; }
        public string SubType { get; set; }
        public string NormBal { get; set; }
        public string InterfaceDetail { get; set; }
        public string Active { get; set; }
        public string SummaryAcct { get; set; }
        public string CashAccrual { get; set; }
        public string CashOffAcct { get; set; }
        public string Notes { get; set; }
        public string Part1 { get; set; }
        public string Part2 { get; set; }
        public string Part3 { get; set; }
        public string Part4 { get; set; }
        public string Part5 { get; set; }
        public string Part6 { get; set; }
        public string AllParts { get; set; }
        public string CrossRefMemAcct { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string ReviewerGroup { get; set; }
        public string POCCActiveYN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APTransLine> bAPTLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMDepartmentCostTypeGLAcct> bEMDGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMDeptCostCodeGLAccount> bEMDOes { get; set; }
    }
}
