//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class GLFinPeriod
    {
        [Key]
		public byte GLCo { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        public byte FiscalPd { get; set; }
        public short FiscalYr { get; set; }
    }
}
