//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HQAttachmentFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HQAttachmentFile()
        {
            this.Thumbnails = new HashSet<HQAttachmentFile>();
        }
    
        public byte HQCo { get; set; }
        public string FormName { get; set; }
        public string KeyField { get; set; }
        public string Description { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string DocName { get; set; }
        [Key]
		public int AttachmentId { get; set; }
        public string TableName { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string OrigFileName { get; set; }
        public string DocAttchYN { get; set; }
        public string CurrentState { get; set; }
        public Nullable<int> AttachmentTypeID { get; set; }
        public string IsEmail { get; set; }
        public long KeyID { get; set; }
        public Nullable<long> FolderId { get; set; }
        public Nullable<int> ThumbnailAttachmentID { get; set; }
    
        public virtual HQCompanyParm Company { get; set; }
        public virtual HQAttachmentFolder Folder { get; set; }
        public virtual HQAttachment Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HQAttachmentFile> Thumbnails { get; set; }
        public virtual HQAttachmentFile FileAttachment { get; set; }
    }
}
