//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HQAttachmentFolder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HQAttachmentFolder()
        {
            this.SubFolders = new HashSet<HQAttachmentFolder>();
            this.Files = new HashSet<HQAttachmentFile>();
        }
    
        [Key]
		public byte HQCo { get; set; }
        [Key]
		public System.Guid UniqueAttchID { get; set; }
        [Key]
		public long FolderId { get; set; }
        public string Description { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<int> AttachmentTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HQAttachmentFolder> SubFolders { get; set; }
        public virtual HQAttachmentFolder Parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HQAttachmentFile> Files { get; set; }
        public virtual HQAttachment Attachment { get; set; }
        public virtual AttachmentType AttachmentType { get; set; }
    }
}
