//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HRPositionTask
    {
        [Key]
		public byte HRCo { get; set; }
        [Key]
		public string PositionCodeId { get; set; }
        [Key]
		public int SeqId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<bool> IsRequired { get; set; }
    
        public virtual HRPosition Position { get; set; }
        public virtual HRTask Task { get; set; }
    }
}
