//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HRPosition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRPosition()
        {
            this.Benefits = new HashSet<HRPositionBenefit>();
            this.Duties = new HashSet<HRPositionDuty>();
            this.Requirements = new HashSet<HRPositionRequirement>();
            this.AppliedPositions = new HashSet<HRAppliedPosition>();
            this.Resources = new HashSet<HRResource>();
            this.PositionRequests = new HashSet<HRPositionRequest>();
            this.DefaultAssets = new HashSet<HRPositionDefaultAsset>();
            this.WAApplications = new HashSet<WAAppliedPosition>();
            this.DefaultTasks = new HashSet<HRPositionTask>();
        }
    
        [Key]
		public byte HRCo { get; set; }
        [Key]
		public string PositionCodeId { get; set; }
        public string JobTitle { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> BegSalary { get; set; }
        public Nullable<decimal> EndSalary { get; set; }
        public string PartTimeYN { get; set; }
        public Nullable<decimal> PartimeHrs { get; set; }
        public string AdYN { get; set; }
        public string AdMode { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string BonusYN { get; set; }
        public Nullable<decimal> BonusPct { get; set; }
        public Nullable<int> ReportLevel { get; set; }
        public string ReportPosition { get; set; }
        public string Type { get; set; }
        public Nullable<int> OpenJobs { get; set; }
        public string Contact { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string ContactFax { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string ShowOnWeb { get; set; }
        public string ReportGroup { get; set; }
        public string WebDescription { get; set; }
        public string WebNotes { get; set; }
        public Nullable<decimal> POLimit { get; set; }
        public string AutoAssignOrg { get; set; }
        public string udActiveDirectoryOU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionBenefit> Benefits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionDuty> Duties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionRequirement> Requirements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRAppliedPosition> AppliedPositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRResource> Resources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionRequest> PositionRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionDefaultAsset> DefaultAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAAppliedPosition> WAApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRPositionTask> DefaultTasks { get; set; }
        public virtual HRCompanyParm HRCompany { get; set; }
    }
}
