//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HRPositionApplicant
    {
        [Key]
		public byte HRCo { get; set; }
        [Key]
		public int RequestId { get; set; }
        [Key]
		public int SeqId { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public int tStatusId { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    
        public virtual HRPositionRequest Request { get; set; }
        public virtual WebApplication Application { get; set; }
        public virtual WebUser ApprovedUser { get; set; }
    }
}
