//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class HRTrafficAccident
    {
        [Key]
		public byte HRCo { get; set; }
        public string Description { get; set; }
        [Key]
		public int HRRef { get; set; }
        [Key]
		public int Seq { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> NumberOfInjuries { get; set; }
    
        public virtual HRResource Resource { get; set; }
    }
}
