//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.PREmployee = new HashSet<Employee>();
            this.Phases = new HashSet<JobPhase>();
            this.DailyEmployeeEntries = new HashSet<DailyEmployeeEntry>();
            this.DailyJobTasks = new HashSet<DNU_DailyJobTask>();
            this.Budgets = new HashSet<ProjectBudget>();
            this.bPMPFs = new HashSet<ProjectFirm>();
            this.PayrollEntries = new HashSet<DEL_DailyPayrollEntry>();
            this.PayrollHourEntries = new HashSet<DTPayrollHour>();
            this.PayrollPerdiemEntries = new HashSet<DTPayrollPerdiem>();
            this.SubJobs = new HashSet<Job>();
            this.bPOHBs = new HashSet<POBatchHeader>();
            this.bPOIBs = new HashSet<POBatchItem>();
            this.POItems = new HashSet<PurchaseOrderItem>();
            this.APLines = new HashSet<APDocumentLine>();
            this.BudgetLines = new HashSet<ProjectBudgetLine>();
            this.POHeaders = new HashSet<PurchaseOrder>();
            this.JobCosts = new HashSet<JobCost>();
            this.ARInvoiceLines = new HashSet<ARTransLine>();
            this.APInvoiceLines = new HashSet<APTransLine>();
            this.vEMLocationHistories = new HashSet<EMLocationLog>();
            this.vEMLocationHistories1 = new HashSet<EMLocationLog>();
            this.CCTransactions = new HashSet<CreditTransactionCode>();
            this.Crews = new HashSet<PMProjectCrew>();
            this.JobPhaseTracks = new HashSet<JobPhaseTrack>();
            this.IntersectJobs = new HashSet<Job>();
            this.bPRTHs = new HashSet<PayrollEntry>();
            this.bPRTBs = new HashSet<PRBatchTimeEntry>();
            this.bAPLBs = new HashSet<APBatchLine>();
            this.DailyFieldTickets = new HashSet<DailyJobTicket>();
            this.PORequests = new HashSet<PORequest>();
            this.budPORLs = new HashSet<PORequestLine>();
            this.BidBoreLines = new HashSet<BidBoreLine>();
            this.BidPackages = new HashSet<BidPackage>();
            this.DailyShopTickets = new HashSet<DailyShopTicket>();
            this.budDTJCs = new HashSet<DTJobPhaseCost>();
            this.DTJobPhases = new HashSet<DTJobPhase>();
            this.budDTEUs = new HashSet<DailyEquipmentUsage>();
        }
    
        [Key]
		public byte JCCo { get; set; }
        [Key]
		public string JobId { get; set; }
        public string Description { get; set; }
        public string ContractId { get; set; }
        public byte JobStatus { get; set; }
        public string BidNumber { get; set; }
        public string LockPhases { get; set; }
        public Nullable<int> ProjectMgr { get; set; }
        public string JobPhone { get; set; }
        public string JobFax { get; set; }
        public string MailAddress { get; set; }
        public string MailCity { get; set; }
        public string MailState { get; set; }
        public string MailZip { get; set; }
        public string MailAddress2 { get; set; }
        public string ShipAddress { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipZip { get; set; }
        public string ShipAddress2 { get; set; }
        public Nullable<short> LiabTemplate { get; set; }
        public byte TaxGroup { get; set; }
        public string TaxCode { get; set; }
        public Nullable<short> InsTemplate { get; set; }
        public decimal MarkUpDiscRate { get; set; }
        public string PRLocalCode { get; set; }
        public string PRStateCode { get; set; }
        public string Certified { get; set; }
        public string EEORegion { get; set; }
        public string SMSACode { get; set; }
        public Nullable<short> CraftTemplate { get; set; }
        public decimal ProjMinPct { get; set; }
        public string Notes { get; set; }
        public string SLCompGroup { get; set; }
        public string POCompGroup { get; set; }
        public Nullable<byte> VendorGroup { get; set; }
        public Nullable<int> ArchEngFirm { get; set; }
        public Nullable<byte> OTSched { get; set; }
        public Nullable<short> PriceTemplate { get; set; }
        public byte HaulTaxOpt { get; set; }
        public string GeoCode { get; set; }
        public string BaseTaxOn { get; set; }
        public string UpdatePlugs { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<int> ContactCode { get; set; }
        public string ClosePurgeFlag { get; set; }
        public Nullable<int> OurFirm { get; set; }
        public string AutoAddItemYN { get; set; }
        public string OverProjNotes { get; set; }
        public string WghtAvgOT { get; set; }
        public decimal HrsPerManDay { get; set; }
        public string AutoGenSubNo { get; set; }
        public Nullable<int> SecurityGroup { get; set; }
        public Nullable<short> DefaultStdDaysDue { get; set; }
        public Nullable<short> DefaultRFIDaysDue { get; set; }
        public string UpdateAPActualsYN { get; set; }
        public string UpdateMSActualsYN { get; set; }
        public string AutoGenPCONo { get; set; }
        public string AutoGenMTGNo { get; set; }
        public string AutoGenRFINo { get; set; }
        public Nullable<short> RateTemplate { get; set; }
        public long KeyID { get; set; }
        public string RevGrpInv { get; set; }
        public string MailCountry { get; set; }
        public string ShipCountry { get; set; }
        public Nullable<System.DateTime> CertDate { get; set; }
        public string AutoGenRFQNo { get; set; }
        public string ApplyEscalators { get; set; }
        public string UseTaxYN { get; set; }
        public string TimesheetRevGroup { get; set; }
        public Nullable<long> PotentialProjectID { get; set; }
        public string PCVisibleInJC { get; set; }
        public Nullable<int> SubmittalReviewDaysResponsibleFirm { get; set; }
        public Nullable<int> SubmittalReviewDaysApprovingFirm { get; set; }
        public Nullable<int> SubmittalReviewDaysRequestingFirm { get; set; }
        public string SubmittalReviewDaysAutoCalcYN { get; set; }
        public Nullable<int> SubmittalApprovingFirm { get; set; }
        public Nullable<int> SubmittalApprovingFirmContact { get; set; }
        public string FourProjectsContainerName { get; set; }
        public Nullable<System.Guid> FourProjectsContainerId { get; set; }
        public string Owner { get; set; }
        public string CrewId { get; set; }
        public Nullable<byte> PipeSize { get; set; }
        public Nullable<short> Footage { get; set; }
        public string GPS { get; set; }
        public string PermitFiled { get; set; }
        public string RigId { get; set; }
        public string EndMarket { get; set; }
        public string DivisionDesc { get; set; }
        public string udMobePhaseId { get; set; }
        public string ParentJobId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string udPriorJobId { get; set; }
        public Nullable<System.DateTime> udCalStartDate { get; set; }
        public string StatusId { get; set; }
        public string JobTypeId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> GanttId { get; set; }
        public Nullable<int> GanttTaskId { get; set; }
        public string IntersectJobId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public Nullable<byte> EMCo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> PREmployee { get; set; }
        public virtual JCContract Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPhase> Phases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEmployeeEntry> DailyEmployeeEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNU_DailyJobTask> DailyJobTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudget> Budgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectFirm> bPMPFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEL_DailyPayrollEntry> PayrollEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTPayrollHour> PayrollHourEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTPayrollPerdiem> PayrollPerdiemEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> SubJobs { get; set; }
        public virtual Job ParentJob { get; set; }
        public virtual HQCompanyParm XXX_HQCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POBatchHeader> bPOHBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POBatchItem> bPOIBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderItem> POItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APDocumentLine> APLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudgetLine> BudgetLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> POHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCost> JobCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTransLine> ARInvoiceLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APTransLine> APInvoiceLines { get; set; }
        public virtual Equipment Rig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMLocationLog> vEMLocationHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMLocationLog> vEMLocationHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditTransactionCode> CCTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMProjectCrew> Crews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPhaseTrack> JobPhaseTracks { get; set; }
        public virtual PMProjectGanttTask ProjectGanttTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> IntersectJobs { get; set; }
        public virtual Job IntersectJob { get; set; }
        public virtual ProjectDivision Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollEntry> bPRTHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRBatchTimeEntry> bPRTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APBatchLine> bAPLBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyJobTicket> DailyFieldTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORequest> PORequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORequestLine> budPORLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLine> BidBoreLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackage> BidPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyShopTicket> DailyShopTickets { get; set; }
        public virtual Crew Crew { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTJobPhaseCost> budDTJCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTJobPhase> DTJobPhases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEquipmentUsage> budDTEUs { get; set; }
        public virtual JCCompanyParm JCCompanyParm { get; set; }
        public virtual HQAttachment budHQAH { get; set; }
    }
}
