//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class JobPhase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPhase()
        {
            this.budDTEEs = new HashSet<DailyEmployeeEntry>();
            this.JobPhaseCosts = new HashSet<JobPhaseCost>();
            this.budDTFPs = new HashSet<DNU_DailyJobTask>();
            this.bPMEDs = new HashSet<ProjectBudgetLine>();
            this.budDTPEs = new HashSet<DEL_DailyPayrollEntry>();
            this.budDTPHs = new HashSet<DTPayrollHour>();
            this.budDTPPs = new HashSet<DTPayrollPerdiem>();
            this.bPOIBs = new HashSet<POBatchItem>();
            this.budAPDLs = new HashSet<APDocumentLine>();
            this.PhaseTracks = new HashSet<JobPhaseTrack>();
            this.bJCCDs = new HashSet<JobCost>();
            this.budCMTCs = new HashSet<CreditTransactionCode>();
            this.bPRTHs = new HashSet<PayrollEntry>();
            this.bPRTBs = new HashSet<PRBatchTimeEntry>();
            this.bAPLBs = new HashSet<APBatchLine>();
            this.bAPTLs = new HashSet<APTransLine>();
            this.bPOITs = new HashSet<PurchaseOrderItem>();
            this.budPORLs1 = new HashSet<PORequestLine>();
            this.budDTJCs = new HashSet<DTJobPhaseCost>();
            this.budDTJTs = new HashSet<DTJobPhase>();
            this.budDTJTs1 = new HashSet<DTJobPhase>();
        }
    
        [Key]
		public byte JCCo { get; set; }
        [Key]
		public string JobId { get; set; }
        [Key]
		public byte PhaseGroupId { get; set; }
        [Key]
		public string PhaseId { get; set; }
        public string Description { get; set; }
        public string ContractId { get; set; }
        public string Item { get; set; }
        public Nullable<decimal> ProjMinPct { get; set; }
        public string ActiveYN { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string InsCode { get; set; }
        public string PhaseType { get; set; }
        public string ParentPhaseId { get; set; }
        public Nullable<int> ProductionSortId { get; set; }
        public string IsMilestone { get; set; }
    
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEmployeeEntry> budDTEEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPhaseCost> JobPhaseCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNU_DailyJobTask> budDTFPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudgetLine> bPMEDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEL_DailyPayrollEntry> budDTPEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTPayrollHour> budDTPHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTPayrollPerdiem> budDTPPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POBatchItem> bPOIBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APDocumentLine> budAPDLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPhaseTrack> PhaseTracks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCost> bJCCDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditTransactionCode> budCMTCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollEntry> bPRTHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRBatchTimeEntry> bPRTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APBatchLine> bAPLBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APTransLine> bAPTLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderItem> bPOITs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORequestLine> budPORLs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTJobPhaseCost> budDTJCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTJobPhase> budDTJTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTJobPhase> budDTJTs1 { get; set; }
    }
}
