//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class LeaveCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveCode()
        {
            this.RequestLines = new HashSet<LeaveRequestLine>();
            this.Usages = new HashSet<LeaveCodeUsage>();
            this.EmployeeLeaves = new HashSet<EmployeeLeave>();
            this.Entries = new HashSet<LeaveEntry>();
        }
    
        [Key]
		public byte PRCo { get; set; }
        [Key]
		public string LeaveCodeId { get; set; }
        public string Description { get; set; }
        public string UM { get; set; }
        public string AccType { get; set; }
        public Nullable<decimal> FixedUnits { get; set; }
        public string FixedFreq { get; set; }
        public string Cap1Freq { get; set; }
        public decimal Cap1Max { get; set; }
        public string Cap2Freq { get; set; }
        public decimal Cap2Max { get; set; }
        public string AvailBalFreq { get; set; }
        public decimal AvailBalMax { get; set; }
        public decimal CarryOver { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string NegLeaveBalWarn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRequestLine> RequestLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveCodeUsage> Usages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveEntry> Entries { get; set; }
    }
}
