//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PMProjectTaskLink
    {
        [Key]
		public byte GTCo { get; set; }
        [Key]
		public int GanttId { get; set; }
        [Key]
		public int LinkId { get; set; }
        public Nullable<int> SourceGanttId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> TargetGanttId { get; set; }
        public Nullable<int> TargetId { get; set; }
        public Nullable<int> LinkType { get; set; }
        public Nullable<decimal> LagDuration { get; set; }
        public long KeyID { get; set; }
    
        public virtual PMProjectGanttTask Source { get; set; }
        public virtual PMProjectGanttTask Target { get; set; }
    }
}
