//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PMProjectGantTaskOwner
    {
        [Key]
		public byte GTCo { get; set; }
        [Key]
		public int GanttId { get; set; }
        [Key]
		public int TaskId { get; set; }
        [Key]
		public int SeqId { get; set; }
        public Nullable<int> OwnerTypeId { get; set; }
        public string OwnerId { get; set; }
        public string OwnerDesc { get; set; }
    
        public virtual PMProjectGanttTask Task { get; set; }
    }
}
