//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class POBatchHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POBatchHeader()
        {
            this.Items = new HashSet<POBatchItem>();
        }
    
        [Key]
		public byte Co { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public int BatchId { get; set; }
        [Key]
		public int BatchSeq { get; set; }
        public string BatchTransType { get; set; }
        public string PO { get; set; }
        public byte VendorGroupId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderedBy { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public byte Status { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string JobId { get; set; }
        public Nullable<byte> INCo { get; set; }
        public string Loc { get; set; }
        public string ShipLoc { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string ShipIns { get; set; }
        public string HoldCode { get; set; }
        public string PayTerms { get; set; }
        public string CompGroup { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> OldVendorGroup { get; set; }
        public Nullable<int> OldVendor { get; set; }
        public string OldDesc { get; set; }
        public Nullable<System.DateTime> OldOrderDate { get; set; }
        public string OldOrderedBy { get; set; }
        public Nullable<System.DateTime> OldExpDate { get; set; }
        public Nullable<byte> OldStatus { get; set; }
        public Nullable<byte> OldJCCo { get; set; }
        public string OldJob { get; set; }
        public Nullable<byte> OldINCo { get; set; }
        public string OldLoc { get; set; }
        public string OldShipLoc { get; set; }
        public string OldAddress { get; set; }
        public string OldCity { get; set; }
        public string OldState { get; set; }
        public string OldZip { get; set; }
        public string OldShipIns { get; set; }
        public string OldHoldCode { get; set; }
        public string OldPayTerms { get; set; }
        public string OldCompGroup { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string Attention { get; set; }
        public string OldAttention { get; set; }
        public Nullable<byte> PayAddressSeq { get; set; }
        public Nullable<byte> OldPayAddressSeq { get; set; }
        public Nullable<byte> POAddressSeq { get; set; }
        public Nullable<byte> OldPOAddressSeq { get; set; }
        public string Address2 { get; set; }
        public string OldAddress2 { get; set; }
        public long KeyID { get; set; }
        public string Country { get; set; }
        public string OldCountry { get; set; }
        public string udOrderedBY { get; set; }
        public Nullable<int> PortalApprover { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POBatchItem> Items { get; set; }
        public virtual APVendor Vendor { get; set; }
    }
}
