//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PRInsuranceCode
    {
        [Key]
		public byte PRCo { get; set; }
        [Key]
		public string State { get; set; }
        [Key]
		public string InsCode { get; set; }
        public string Description { get; set; }
        public string ApplyLimit { get; set; }
        public Nullable<decimal> EarnLimit { get; set; }
        public string UseThreshold { get; set; }
        public decimal ThresholdRate { get; set; }
        public string OverrideInsCode { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
    }
}
