//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class ProjectBudgetCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectBudgetCode()
        {
            this.DailyJobTasks = new HashSet<DNU_DailyJobTask>();
            this.BudgetLines = new HashSet<ProjectBudgetLine>();
            this.Phases = new HashSet<ProjectBudgetCodeCalPhase>();
            this.budBDCIs = new HashSet<BidCostItem>();
            this.budBDBIs = new HashSet<BidBoreLineCostItem>();
            this.budDTFPs1 = new HashSet<DNU_DailyJobTask>();
            this.budJCPTs = new HashSet<JobPhaseTrack>();
            this.budJCPTs1 = new HashSet<JobPhaseTrack>();
            this.budDTJCs = new HashSet<DTJobPhaseCost>();
            this.budDTJTs1 = new HashSet<DTJobPhase>();
        }
    
        [Key]
		public byte PMCo { get; set; }
        [Key]
		public string BudgetCodeId { get; set; }
        public string Description { get; set; }
        public string Active { get; set; }
        public string CostLevel { get; set; }
        public Nullable<byte> PhaseGroupId { get; set; }
        public string PhaseId { get; set; }
        public Nullable<byte> CostTypeId { get; set; }
        public string UM { get; set; }
        public decimal UnitCost { get; set; }
        public decimal HrsPerUnit { get; set; }
        public decimal Percentage { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string Basis { get; set; }
        public string TimeUM { get; set; }
        public decimal Rate { get; set; }
        public string ExcludeFromLookups { get; set; }
        public Nullable<decimal> Radius { get; set; }
        public string Hardness { get; set; }
        public string RockOnly { get; set; }
        public string Category { get; set; }
        public Nullable<int> udGroundDensityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNU_DailyJobTask> DailyJobTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudgetLine> BudgetLines { get; set; }
        public virtual UnitofMeasure UnitofMeasure { get; set; }
        public virtual CostType CostType { get; set; }
        public virtual PhaseMaster Phase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudgetCodeCalPhase> Phases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidCostItem> budBDCIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidBoreLineCostItem> budBDBIs { get; set; }
        public virtual HQCompanyParm Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNU_DailyJobTask> budDTFPs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPhaseTrack> budJCPTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPhaseTrack> budJCPTs1 { get; set; }
        public virtual PMCompanyParm PMCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTJobPhaseCost> budDTJCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTJobPhase> budDTJTs1 { get; set; }
    }
}
