//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.Items = new HashSet<PurchaseOrderItem>();
            this.APDocumentLines = new HashSet<APDocumentLine>();
            this.APDocumentSeqs = new HashSet<APDocumentSeq>();
            this.budCMTCs = new HashSet<CreditTransactionCode>();
            this.bAPLBs = new HashSet<APBatchLine>();
        }
    
        [Key]
		public byte POCo { get; set; }
        [Key]
		public string PO { get; set; }
        public byte VendorGroupId { get; set; }
        public int VendorId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderedBy { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public byte Status { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string JobId { get; set; }
        public Nullable<byte> INCo { get; set; }
        public string Loc { get; set; }
        public string ShipLoc { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string ShipIns { get; set; }
        public string HoldCode { get; set; }
        public string PayTerms { get; set; }
        public string CompGroup { get; set; }
        public Nullable<System.DateTime> MthClosed { get; set; }
        public Nullable<System.DateTime> InUseMth { get; set; }
        public Nullable<int> InUseBatchId { get; set; }
        public string Approved { get; set; }
        public string ApprovedBy { get; set; }
        public string Purge { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> AddedMth { get; set; }
        public Nullable<int> AddedBatchID { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string Attention { get; set; }
        public Nullable<byte> PayAddressSeq { get; set; }
        public Nullable<byte> POAddressSeq { get; set; }
        public string Address2 { get; set; }
        public long KeyID { get; set; }
        public string Country { get; set; }
        public Nullable<int> POCloseBatchID { get; set; }
        public string DocType { get; set; }
        public string udOrderedBY { get; set; }
        public Nullable<System.DateTime> targetInUseMth { get; set; }
        public Nullable<int> targetInUseBatchId { get; set; }
        public Nullable<int> udPortalApprover { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderItem> Items { get; set; }
        public virtual HQCompanyParm XXX_Company { get; set; }
        public virtual APVendor Vendor { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APDocumentLine> APDocumentLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APDocumentSeq> APDocumentSeqs { get; set; }
        public virtual POCompanyParm POCompanyParm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditTransactionCode> budCMTCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APBatchLine> bAPLBs { get; set; }
    }
}
