//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class SMRequestLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMRequestLine()
        {
            this.FollowupRequests = new HashSet<SMRequestLine>();
        }
    
        [Key]
		public byte SMCo { get; set; }
        [Key]
		public int RequestId { get; set; }
        [Key]
		public int LineId { get; set; }
        public string tEquipmentId { get; set; }
        public string RequestComments { get; set; }
        public int StatusId { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public string WorkOrderId { get; set; }
        public Nullable<short> WOItemId { get; set; }
        public Nullable<int> ServiceItemId { get; set; }
        public Nullable<int> WorkFlowId { get; set; }
        public Nullable<bool> IsEquipmentDisabled { get; set; }
        public Nullable<bool> IsEmergancy { get; set; }
        public Nullable<bool> IsFieldRepair { get; set; }
        public Nullable<bool> FollowUpRequired { get; set; }
        public Nullable<int> FollowUpRequestId { get; set; }
        public Nullable<int> FollowUpLineId { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<System.DateTime> EstServiceDate { get; set; }
        public Nullable<System.DateTime> ActServiceDate { get; set; }
        public Nullable<decimal> ActServiceCost { get; set; }
        public Nullable<decimal> ActServiceHours { get; set; }
        public string CompletedComments { get; set; }
        public Nullable<decimal> ActServiceLaborCost { get; set; }
        public Nullable<decimal> ActServiceMaterialCost { get; set; }
        public string AssignedLocation { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> EstHours { get; set; }
        public Nullable<bool> EMWorkOrderAdd { get; set; }
        public Nullable<int> ShopGroupId { get; set; }
        public string ShopId { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public Nullable<int> AsignedEmployeeId { get; set; }
        public Nullable<int> ForumId { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual EMWorkOrderItem WorkorderItem { get; set; }
        public virtual SMRequest Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMRequestLine> FollowupRequests { get; set; }
        public virtual SMRequestLine FollowupRequest { get; set; }
        public virtual WorkFlow WorkFlow { get; set; }
        public virtual Employee AssignedEmployee { get; set; }
        public virtual EMShop bEMSX { get; set; }
        public virtual HQAttachment HQAttachment { get; set; }
        public virtual Forum Forum { get; set; }
    }
}
