//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfile()
        {
            this.bHQBCs = new HashSet<Batch>();
        }
    
        [Key]
		public string VPUserName { get; set; }
        public string ShowRates { get; set; }
        public string HotKeyForm { get; set; }
        public string RestrictedBatches { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string EMail { get; set; }
        public string ConfirmUpdate { get; set; }
        public byte DefaultCompany { get; set; }
        public string EnterAsTab { get; set; }
        public string ExtendControls { get; set; }
        public string SavePrinterSettings { get; set; }
        public string SmartCursor { get; set; }
        public string ToolTipHelp { get; set; }
        public string Project { get; set; }
        public Nullable<byte> PRGroup { get; set; }
        public Nullable<System.DateTime> PREndDate { get; set; }
        public Nullable<System.DateTime> JBBillMth { get; set; }
        public Nullable<int> JBBillNumber { get; set; }
        public string MenuColWidth { get; set; }
        public string LastNode { get; set; }
        public string LastSubFolder { get; set; }
        public string MinimizeUse { get; set; }
        public string AccessibleOnly { get; set; }
        public string ViewOptions { get; set; }
        public string ReportOptions { get; set; }
        public Nullable<int> SmartCursorColor { get; set; }
        public Nullable<int> AccentColor1 { get; set; }
        public string UseColorGrad { get; set; }
        public Nullable<int> FormColor1 { get; set; }
        public Nullable<int> FormColor2 { get; set; }
        public Nullable<byte> GradDirection { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public string MenuAdmin { get; set; }
        public Nullable<int> AccentColor2 { get; set; }
        public Nullable<int> ReqFieldColor { get; set; }
        public Nullable<byte> IconSize { get; set; }
        public Nullable<byte> FontSize { get; set; }
        public string FormAdmin { get; set; }
        public string MultiFormInstance { get; set; }
        public Nullable<int> PayCategory { get; set; }
        public string HideModFolders { get; set; }
        public Nullable<byte> FolderSize { get; set; }
        public string Job { get; set; }
        public string Contract { get; set; }
        public byte MenuInfo { get; set; }
        public Nullable<int> LastReportID { get; set; }
        public Nullable<int> ColorSchemeID { get; set; }
        public Nullable<int> MappingID { get; set; }
        public string ImportId { get; set; }
        public string ImportTemplate { get; set; }
        public Nullable<System.DateTime> JBTMBillMth { get; set; }
        public Nullable<int> JBTMBillNumber { get; set; }
        public string PMTemplate { get; set; }
        public string MergeGridKeys { get; set; }
        public Nullable<int> MaxLookupRows { get; set; }
        public string PMViewName { get; set; }
        public Nullable<int> DefaultColorSchemeID { get; set; }
        public string AltGridRowColors { get; set; }
        public long KeyID { get; set; }
        public Nullable<byte> HRCo { get; set; }
        public Nullable<int> HRRef { get; set; }
        public string DefaultDestType { get; set; }
        public string WindowsUserName { get; set; }
        public string SelectedTemplate { get; set; }
        public string RQEntyHeaderID { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public Nullable<int> Employee { get; set; }
        public string RQQuoteEditHeaderID { get; set; }
        public byte MyTimesheetRole { get; set; }
        public string AttachmentGrouping { get; set; }
        public string IsHelpUpToDate { get; set; }
        public Nullable<int> LabelBackgroundColor { get; set; }
        public Nullable<int> LabelTextColor { get; set; }
        public Nullable<int> LabelBorderStyle { get; set; }
        public string ShowLogoPanel { get; set; }
        public string ShowMainToolbar { get; set; }
        public short UserType { get; set; }
        public string PMErrorCorrectionSubcontracts { get; set; }
        public string PMErrorCorrectionSubcontractCOs { get; set; }
        public string PMErrorCorrectionPurchaseOrders { get; set; }
        public string PMErrorCorrectionPurchaseOrderCOs { get; set; }
        public string SaveLastUsedParameters { get; set; }
        public byte ReportViewerOptions { get; set; }
        public Nullable<int> ThumbnailMaxCount { get; set; }
        public string FourProjectsUserName { get; set; }
        public string FourProjectsPassword { get; set; }
        public string SendViaSmtp { get; set; }
        public Nullable<System.DateTime> DeactivatedDate { get; set; }
        public string AutoLogOutFlag { get; set; }
        public string CSAllowDocEdit { get; set; }
        public string CSSelectAllAttachments { get; set; }
        public string LookupColumnAutoSize { get; set; }
        public string AllowExternalLogin { get; set; }
        public int LoginFailCount { get; set; }
        public Nullable<System.DateTime> LockoutDateTime { get; set; }
        public byte AttachmentListerStyle { get; set; }
        public string ShowUnsavedChangesOnStartup { get; set; }
        public Nullable<int> PageSize { get; set; }
        public string DisallowSelfSecurityYN { get; set; }
        public string SuppressMaxWarningRows { get; set; }
        public string EnableSharedSearch { get; set; }
        public string AatrixInstallLocation { get; set; }
    
        public virtual Employee PREmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> bHQBCs { get; set; }
    }
}
