//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class vAPTran
    {
        [Key]
		public byte APCo { get; set; }
        [Key]
		public System.DateTime Mth { get; set; }
        [Key]
		public int APTransId { get; set; }
        [Key]
		public byte VendorGroup { get; set; }
        [Key]
		public int VendorId { get; set; }
        public string InvId { get; set; }
        public string APRef { get; set; }
        public string Description { get; set; }
        [Key]
		public System.DateTime InvDate { get; set; }
        public Nullable<System.DateTime> DiscDate { get; set; }
        [Key]
		public System.DateTime DueDate { get; set; }
        [Key]
		public decimal InvTotal { get; set; }
        public string HoldCode { get; set; }
        public string PayControl { get; set; }
        [Key]
		public string PayMethod { get; set; }
        [Key]
		public byte CMCo { get; set; }
        public Nullable<short> CMAcct { get; set; }
        [Key]
		public string PrePaidYN { get; set; }
        public Nullable<System.DateTime> PrePaidMth { get; set; }
        public Nullable<System.DateTime> PrePaidDate { get; set; }
        public string PrePaidChk { get; set; }
        public Nullable<byte> PrePaidSeq { get; set; }
        [Key]
		public string PrePaidProcYN { get; set; }
        [Key]
		public string V1099YN { get; set; }
        public string V1099Type { get; set; }
        public Nullable<byte> V1099Box { get; set; }
        [Key]
		public string PayOverrideYN { get; set; }
        public string PayName { get; set; }
        public string PayAddress { get; set; }
        public string PayCity { get; set; }
        public string PayState { get; set; }
        public string PayZip { get; set; }
        [Key]
		public string OpenYN { get; set; }
        public Nullable<System.DateTime> InUseMth { get; set; }
        public Nullable<int> InUseBatchId { get; set; }
        [Key]
		public int BatchId { get; set; }
        [Key]
		public string Purge { get; set; }
        [Key]
		public string InPayControl { get; set; }
        public string PayAddInfo { get; set; }
        public string DocName { get; set; }
        public Nullable<byte> AddendaTypeId { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<short> DLcode { get; set; }
        public string TaxFormCode { get; set; }
        public Nullable<System.DateTime> TaxPeriodEndDate { get; set; }
        public string AmountType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AmtType2 { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public string AmtType3 { get; set; }
        public Nullable<decimal> Amount3 { get; set; }
        [Key]
		public string SeparatePayYN { get; set; }
        [Key]
		public string ChkRev { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<byte> AddressSeq { get; set; }
        [Key]
		public long KeyID { get; set; }
        public string PayCountry { get; set; }
        public Nullable<long> SLKeyID { get; set; }
        public string DisplayDescription { get; set; }
        public string SearchStr { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> AttchCnt { get; set; }
    }
}
