//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class vAudit
    {
        public string TableName { get; set; }
        public Nullable<byte> Co { get; set; }
        public string RecType { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime DateTime { get; set; }
        public string UserName { get; set; }
        [Key]
		public long AuditID { get; set; }
        public string HostName { get; set; }
        [Key]
		public string EntityName { get; set; }
        [Key]
		public string EntityKey { get; set; }
    }
}
