//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class vBid
    {
        [Key]
		public byte BDCo { get; set; }
        [Key]
		public int BidId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> BidDate { get; set; }
        public string Owner { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string PipeSizeStr { get; set; }
        public string JobIdStr { get; set; }
        public Nullable<decimal> DirtRevenue { get; set; }
        public Nullable<decimal> RockRevenue { get; set; }
        public string AssignedToStr { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<decimal> Footage { get; set; }
        [Key]
		public string SearchString { get; set; }
        public string Division { get; set; }
        public Nullable<decimal> PercentChance { get; set; }
        public Nullable<decimal> DirtCost { get; set; }
        public Nullable<decimal> RockCost { get; set; }
        public string StatusDescription { get; set; }
        [Key]
		public int Year { get; set; }
        public Nullable<int> Month { get; set; }
        [Key]
		public int IndustryId { get; set; }
        public string Industry { get; set; }
        public Nullable<int> NumberOfBores { get; set; }
    }
}
