//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class vFormHeader
    {
        public string Form { get; set; }
        public string Title { get; set; }
        public Nullable<byte> FormType { get; set; }
        public string ShowOnMenu { get; set; }
        public string IconKey { get; set; }
        public string ViewName { get; set; }
        public string JoinClause { get; set; }
        public string WhereClause { get; set; }
        public string AssemblyName { get; set; }
        public string FormClassName { get; set; }
        public string ProgressClip { get; set; }
        public Nullable<short> FormNumber { get; set; }
        public string HelpFile { get; set; }
        public string HelpKeyword { get; set; }
        public Nullable<byte> NotesTab { get; set; }
        public Nullable<byte> FormattedNotesTab { get; set; }
        public string LoadProc { get; set; }
        public string LoadParams { get; set; }
        public string PostedTable { get; set; }
        public string AllowAttachments { get; set; }
        public Nullable<byte> Version { get; set; }
        public string Mod { get; set; }
        [Key]
		public string HasProgressIndicator { get; set; }
        public string CoColumn { get; set; }
        public string BatchProcessForm { get; set; }
        public string OrderByClause { get; set; }
        [Key]
		public string Custom { get; set; }
        public Nullable<byte> DefaultTabPage { get; set; }
        [Key]
		public byte LicLevel { get; set; }
        [Key]
		public string AllowCustomFields { get; set; }
        public string CustomFieldTable { get; set; }
        public string SecurityForm { get; set; }
        [Key]
		public string DetailFormSecurity { get; set; }
        public string V5xForm { get; set; }
        public string QueryView { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string ShowFormProperties { get; set; }
        public string ShowFieldProperties { get; set; }
        public Nullable<int> DefaultAttachmentTypeID { get; set; }
        public string AlwayInheritAddUpdateDelete { get; set; }
        public string CustomFieldView { get; set; }
        [Key]
		public string AdminSupportForm { get; set; }
        public string FormSearch { get; set; }
    }
}
