//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class vJob
    {
        [Key]
		public byte JCCo { get; set; }
        [Key]
		public string JobId { get; set; }
        public Nullable<int> BidId { get; set; }
        public Nullable<int> BoreId { get; set; }
        public string JobDescription { get; set; }
        public string ParentJobId { get; set; }
        public string ParentJobDescription { get; set; }
        public string Division { get; set; }
        public string EndMarket { get; set; }
        public byte JobStatus { get; set; }
        public string StatusDescription { get; set; }
        public string CrewId { get; set; }
        public string CrewDescription { get; set; }
        public string RigId { get; set; }
        public string RigDescription { get; set; }
        public string ContractId { get; set; }
        public Nullable<int> Customer { get; set; }
        public string CustName { get; set; }
        public Nullable<int> IsRock { get; set; }
        public Nullable<short> Footage { get; set; }
        public decimal Inv_Amount { get; set; }
        public decimal Job_Cost { get; set; }
        public Nullable<decimal> Act_Gross { get; set; }
        public Nullable<decimal> ACTGM { get; set; }
        public decimal BgtLFPrice { get; set; }
        public Nullable<decimal> BgtCurFootage { get; set; }
        public decimal BgtCurRevenue { get; set; }
        public decimal BgtCurCost { get; set; }
        public Nullable<decimal> BGT_CurGross { get; set; }
        public Nullable<decimal> BgtCurGM { get; set; }
        public Nullable<decimal> BgtFootage { get; set; }
        public decimal BgtRevenue { get; set; }
        public decimal BgtCost { get; set; }
        public Nullable<decimal> BGT_Gross { get; set; }
        public Nullable<decimal> BGTGM { get; set; }
        public Nullable<decimal> PackageGM { get; set; }
        public Nullable<byte> PipeSize { get; set; }
        [Key]
		public long KeyID { get; set; }
        public Nullable<long> ParentKeyId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        [Key]
		public string JobStatusDescription { get; set; }
        public Nullable<int> StatusId { get; set; }
        [Key]
		public int HasAttachments { get; set; }
        public string JobTypeId { get; set; }
        public string JobType { get; set; }
        public Nullable<int> JobYear { get; set; }
        public string JobIdDescription { get; set; }
        public string PipeSizeDescription { get; set; }
        public string RigCategory { get; set; }
        public string RigCategoryDescription { get; set; }
        public Nullable<decimal> RevPerFoot { get; set; }
        [Key]
		public decimal Job_Cost_UnPosted { get; set; }
        public Nullable<decimal> Act_GrossAdj { get; set; }
        public Nullable<decimal> ACTGMADJ { get; set; }
        public Nullable<System.DateTime> JobMth { get; set; }
    }
}
