//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class vJobForecastedCost
    {
        [Key]
		public byte JCCo { get; set; }
        public Nullable<System.DateTime> Mth { get; set; }
        public Nullable<int> CostTrans { get; set; }
        public string Job { get; set; }
        [Key]
		public byte PhaseGroupId { get; set; }
        [Key]
		public string Phase { get; set; }
        public Nullable<byte> CostType { get; set; }
        public Nullable<int> GroundDensityId { get; set; }
        [Key]
		public string BudgetCodeId { get; set; }
        [Key]
		public string SubBudgetCodeId { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public string JCTransType { get; set; }
        [Key]
		public string Source { get; set; }
        public string Description { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> InUseBatchId { get; set; }
        public Nullable<byte> GLCo { get; set; }
        public string GLTransAcct { get; set; }
        public string GLOffsetAcct { get; set; }
        public Nullable<byte> ReversalStatus { get; set; }
        public string UM { get; set; }
        public Nullable<decimal> ActualUnitCost { get; set; }
        public string PerECM { get; set; }
        public Nullable<decimal> ActualHours { get; set; }
        public Nullable<decimal> ActualUnits { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public Nullable<decimal> ProgressCmplt { get; set; }
        public Nullable<decimal> EstHours { get; set; }
        public Nullable<decimal> EstUnits { get; set; }
        public Nullable<decimal> EstCost { get; set; }
        public Nullable<decimal> ProjHours { get; set; }
        public Nullable<decimal> ProjUnits { get; set; }
        public Nullable<decimal> ProjCost { get; set; }
        public Nullable<decimal> ForecastHours { get; set; }
        public Nullable<decimal> ForecastUnits { get; set; }
        public Nullable<decimal> ForecastCost { get; set; }
        public string PostedUM { get; set; }
        public Nullable<decimal> PostedUnits { get; set; }
        public Nullable<decimal> PostedUnitCost { get; set; }
        public string PostedECM { get; set; }
        public Nullable<decimal> PostTotCmUnits { get; set; }
        public Nullable<decimal> PostRemCmUnits { get; set; }
        public Nullable<decimal> TotalCmtdUnits { get; set; }
        public Nullable<decimal> TotalCmtdCost { get; set; }
        public Nullable<decimal> RemainCmtdUnits { get; set; }
        public Nullable<decimal> RemainCmtdCost { get; set; }
        public string DeleteFlag { get; set; }
        public Nullable<short> AllocCode { get; set; }
        public string ACO { get; set; }
        public string ACOItem { get; set; }
        public Nullable<byte> PRCo { get; set; }
        public Nullable<int> Employee { get; set; }
        public string Craft { get; set; }
        public string Class { get; set; }
        public string Crew { get; set; }
        public Nullable<decimal> EarnFactor { get; set; }
        public Nullable<short> EarnType { get; set; }
        public Nullable<byte> Shift { get; set; }
        public Nullable<short> LiabilityType { get; set; }
        public Nullable<byte> VendorGroup { get; set; }
        public Nullable<int> Vendor { get; set; }
        public Nullable<byte> APCo { get; set; }
        public Nullable<int> APTrans { get; set; }
        public Nullable<short> APLine { get; set; }
        public string APRef { get; set; }
        public string PO { get; set; }
        public Nullable<short> POItem { get; set; }
        public string SL { get; set; }
        public Nullable<short> SLItem { get; set; }
        public string MO { get; set; }
        public Nullable<short> MOItem { get; set; }
        public Nullable<byte> MatlGroup { get; set; }
        public string Material { get; set; }
        public Nullable<byte> INCo { get; set; }
        public string Loc { get; set; }
        public Nullable<decimal> INStdUnitCost { get; set; }
        public string INStdECM { get; set; }
        public string INStdUM { get; set; }
        public Nullable<int> MSTrans { get; set; }
        public string MSTicket { get; set; }
        public string JBBillStatus { get; set; }
        public Nullable<System.DateTime> JBBillMonth { get; set; }
        public Nullable<int> JBBillNumber { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public string EMEquip { get; set; }
        public string EMRevCode { get; set; }
        public Nullable<byte> EMGroup { get; set; }
        public Nullable<int> EMTrans { get; set; }
        public Nullable<byte> TaxType { get; set; }
        public Nullable<byte> TaxGroup { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> TaxBasis { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<byte> SrcJCCo { get; set; }
        public Nullable<long> KeyID { get; set; }
        public Nullable<decimal> TotalCmtdTax { get; set; }
        public Nullable<decimal> RemCmtdTax { get; set; }
        public Nullable<byte> OffsetGLCo { get; set; }
        public Nullable<int> POItemLine { get; set; }
        public string udCrew { get; set; }
        public Nullable<long> SMWorkCompletedID { get; set; }
        public Nullable<byte> SMCo { get; set; }
        public Nullable<int> SMWorkOrder { get; set; }
        public Nullable<int> SMScope { get; set; }
        public string PMCostProjection { get; set; }
        public string udZionsID { get; set; }
        public string udWEXID { get; set; }
        public Nullable<int> udTicketId { get; set; }
    }
}
