//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class vPOItemLine
    {
        [Key]
		public long KeyID { get; set; }
        public long POITKeyID { get; set; }
        public byte POCo { get; set; }
        public string PO { get; set; }
        public short POItemId { get; set; }
        public int POItemLine { get; set; }
        public byte ItemType { get; set; }
        public byte PostToCo { get; set; }
        public Nullable<byte> JCCo { get; set; }
        public string Job { get; set; }
        public Nullable<byte> PhaseGroup { get; set; }
        public string Phase { get; set; }
        public Nullable<byte> JCCType { get; set; }
        public Nullable<byte> INCo { get; set; }
        public string Loc { get; set; }
        public Nullable<byte> EMCo { get; set; }
        public Nullable<byte> EMGroup { get; set; }
        public string EquipmentId { get; set; }
        public string CompType { get; set; }
        public string Component { get; set; }
        public string CostCode { get; set; }
        public Nullable<byte> EMCType { get; set; }
        public string WO { get; set; }
        public Nullable<short> WOItem { get; set; }
        public Nullable<byte> SMCo { get; set; }
        public Nullable<int> SMWorkOrder { get; set; }
        public Nullable<int> SMScope { get; set; }
        public Nullable<byte> TaxGroup { get; set; }
        public Nullable<byte> TaxType { get; set; }
        public string TaxCode { get; set; }
        public decimal TaxRate { get; set; }
        public decimal GSTRate { get; set; }
        public byte GLCo { get; set; }
        public string GLAcct { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public Nullable<int> PayCategory { get; set; }
        public Nullable<byte> PayType { get; set; }
        public decimal OrigUnits { get; set; }
        public decimal OrigCost { get; set; }
        public decimal OrigTax { get; set; }
        public decimal CurUnits { get; set; }
        public decimal CurCost { get; set; }
        public decimal CurTax { get; set; }
        public decimal RecvdUnits { get; set; }
        public decimal RecvdCost { get; set; }
        public decimal BOUnits { get; set; }
        public decimal BOCost { get; set; }
        public decimal InvUnits { get; set; }
        public decimal InvCost { get; set; }
        public decimal InvTax { get; set; }
        public decimal InvMiscAmt { get; set; }
        public decimal RemUnits { get; set; }
        public decimal RemCost { get; set; }
        public decimal RemTax { get; set; }
        public decimal JCCmtdTax { get; set; }
        public decimal JCRemCmtdTax { get; set; }
        public decimal TotalUnits { get; set; }
        public decimal TotalCost { get; set; }
        public decimal TotalTax { get; set; }
        public System.DateTime PostedDate { get; set; }
        public Nullable<System.DateTime> JCMonth { get; set; }
        public Nullable<System.DateTime> InUseMth { get; set; }
        public Nullable<int> InUseBatchId { get; set; }
        public string Notes { get; set; }
        public string PurgeYN { get; set; }
        public string LineDelete { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public Nullable<int> SMWorkCompleted { get; set; }
        public Nullable<byte> SMPhaseGroup { get; set; }
        public string SMPhase { get; set; }
        public Nullable<byte> SMJCCostType { get; set; }
        public Nullable<short> SMCostType { get; set; }
        public Nullable<System.DateTime> targetInUseMth { get; set; }
        public Nullable<int> targetInUseBatchId { get; set; }
    }
}
