//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class WAApplicantDrugTest
    {
        [Key]
		public int ApplicantId { get; set; }
        [Key]
		public int ApplicationId { get; set; }
        [Key]
		public int SeqId { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string TestType { get; set; }
        public string Location { get; set; }
        public string TestStatusId { get; set; }
        public string Results { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
    
        public virtual WebApplication Applicaiton { get; set; }
    }
}
