//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class WAWorkExperience
    {
        [Key]
		public int ApplicantId { get; set; }
        [Key]
		public int ApplicationId { get; set; }
        [Key]
		public int SeqId { get; set; }
        public string Employer { get; set; }
        public string AddressCity { get; set; }
        public string AddressState { get; set; }
        public string AddressStreet { get; set; }
        public string AddressZip { get; set; }
        public string JobDuties { get; set; }
        public string Position { get; set; }
        public string ReasonForLeaving { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string SupervisorName { get; set; }
        public Nullable<System.DateTime> WorkFromDate { get; set; }
        public Nullable<System.DateTime> WorkToDate { get; set; }
        public string WorkPhone { get; set; }
    
        public virtual WebApplication Application { get; set; }
    }
}
