//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class WebControllerSub
    {
        [Key]
		public int FormId { get; set; }
        [Key]
		public int SubFormId { get; set; }
        public Nullable<byte> InheritAccessFromParent { get; set; }
    
        public virtual WebController Controller { get; set; }
        public virtual WebController SubController { get; set; }
    }
}
