//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portal.Code.Data.VP
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class WorkFlowUser
    {
        [Key]
		public byte WFCo { get; set; }
        [Key]
		public int WorkFlowId { get; set; }
        [Key]
		public int SeqId { get; set; }
        [Key]
		public string AssignedTo { get; set; }
        public System.DateTime AssignedOn { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<System.DateTime> EmailedDate { get; set; }
        public Nullable<int> NotificationId { get; set; }
        public Nullable<System.Guid> UniqueAttchID { get; set; }
        public long KeyID { get; set; }
        public string Comments { get; set; }
    
        public virtual WorkFlowSequance Sequance { get; set; }
        public virtual WebUser AssignedUser { get; set; }
        public virtual WorkFlow WorkFlow { get; set; }
    }
}
