using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DB.Infrastructure.ViewPointDB.Data
{
	public partial class PayrollEntry
	{
        

        public PRBatchTimeEntry ToCorrectionTimeEntry(Batch batch)
		{
			var result = new PRBatchTimeEntry()
			{
				db = batch.db,
				Batch = batch,

				Employee = this.Employee,
				EarnCode = this.EarnCode,
				JCJob = this.JCJob,
				EMEquipment = this.EMEquipment,
				IsInBatch = false,
				Co = batch.Co,
				Mth = batch.Mth,
				BatchId = this.BatchId,
				//BatchSeq = this.BatchSeq,
				BatchTransType = "C",
				EmployeeId = this.EmployeeId,
				PaySeq = this.PaySeq,
				PostSeq = this.PostSeq,
				Type = this.Type,
				DayNum = 0,
				PostDate = this.PostDate,
				JCCo = this.JCCo,
				JobId = this.JobId,
				PhaseGroupId = this.PhaseGroupId,
				PhaseId = this.PhaseId,
				GLCo = this.GLCo,
				EMCo = this.EMCo,
				WO = this.WO,
				WOItem = this.WOItem,
				EquipmentId = this.EquipmentId,
				EMGroupId = this.EMGroupId,
				CostCodeId = this.CostCode,
				CompType = this.CompType,
				Component = this.Component,
				RevCode = this.RevCode,
				EquipCType = this.EquipCType,
				UsageUnits = this.UsageUnits,
				TaxState = this.TaxState,
				LocalCode = this.LocalCode,
				UnempState = this.UnempState,
				InsState = this.InsState,
				InsCode = this.InsCode,
				PRDept = this.PRDept,
				CrewId = this.CrewId,
				Cert = this.Cert,
				Craft = this.Craft,
				Class = this.Class,
				EarnCodeId = this.EarnCodeId,
				Shift = this.Shift,
				Hours = this.Hours,
				Rate = this.Rate,
				Amt = this.Amt,
				OldEmployee = this.EmployeeId,
				OldPaySeq = this.PaySeq,
				OldPostSeq = this.PostSeq,
				OldPREndDate = this.PREndDate,
				OldPRGroup = this.PRGroup,
				OldType = this.Type,
				OldPostDate = this.PostDate,
				OldJCCo = this.JCCo,
				OldJob = this.JobId,
				OldPhaseGroup = this.PhaseGroupId,
				OldPhase = this.PhaseId,
				OldGLCo = this.GLCo,
				OldEMCo = this.EMCo,
				OldWO = this.WO,
				OldWOItem = this.WOItem,
				OldEquipment = this.EquipmentId,
				OldEMGroup = this.EMGroupId,
				OldCostCode = this.CostCode,
				OldCompType = this.CompType,
				OldComponent = this.Component,
				OldRevCode = this.RevCode,
				OldEquipCType = this.EquipCType,
				OldUsageUnits = this.UsageUnits,
				OldTaxState = this.TaxState,
				OldLocalCode = this.LocalCode,
				OldUnempState = this.UnempState,
				OldInsState = this.InsState,
				OldInsCode = this.InsCode,
				OldPRDept = this.PRDept,
				OldCrew = this.CrewId,
				OldCert = this.Cert,
				OldCraft = this.Craft,
				OldClass = this.Class,
				OldEarnCode = this.EarnCodeId,
				OldShift = this.Shift,
				OldHours = this.Hours,
				OldRate = this.Rate,
				OldAmt = this.Amt,
				Memo = this.Memo,
				OldMemo = this.Memo,
				EquipPhase = this.EquipPhase,
				OldEquipPhase = this.EquipPhase,
				SMCo = this.SMCo,
				SMWorkOrder = this.SMWorkOrder,
				SMScope = this.SMScope,
				SMPayType = this.SMPayType,
				OldSMCo = this.SMCo,
				OldSMWorkOrder = this.SMWorkOrder,
				OldSMScope = this.SMScope,
				OldSMPayType = this.SMPayType,
				SMCostType = this.SMCostType,
				OldSMCostType = this.SMCostType,
				SMJCCostType = this.SMJCCostType,
				OldSMJCCostType = this.SMJCCostType,
				StartTime = this.StartTime,
				StopTime = this.StopTime,
				BreakHours = this.BreakHours,
				OldStartTime = this.StartTime,
				OldStopTime = this.StopTime,
				OldBreakHours = this.BreakHours,
				EquipSMCostType = this.EquipSMCostType,
				OldEquipSMCostType = this.EquipSMCostType,
				udTicketId = this.udTicketId,
				udTicketLineId = this.udTicketLineId,
				udDTCo = this.udDTCo,
			};

			return result;
		}
	}
}
